### ISSUE TITLE
Battery issue on WSDCGQ11LM

### ISSUE THREAD

**Issue by Smanar** [dresden-elektronik/deconz-rest-plugin#1450]
Hello, I know someone with a batterie issue on the Xiaomi temperature/humidity/barometer sensor.

```
2: {
config: {
battery: null,
offset: 0,
on: true,
reachable: true
},
ep: 1,
etag: "7ec0db25ce0251f236fbe6663d2da3c5",
manufacturername: "LUMI",
modelid: "lumi.weather",
name: "Temperature",
state: {
lastupdated: "2019-04-19T11:18:11",
temperature: 1876
},
swversion: "20161129",
type: "ZHATemperature",
uniqueid: "00:15:8d:00:02:c9:9e:08-01-0402"
},
```

His installation is running since 3 days. All sensors are working fine, except 2 sensors, all the same.
From my memory this sensor send periodically data with temp/humi/baro/batterie by attribute ff01. How it can be possible not have batterie information after 3 days ?

Version 2.05.63
firmware 26480700

**Comment by bubffm** [comment]
This has been fixed in 2.05.65 and should be closed

**Comment by Smanar** [comment]
Yep, I know, but I m waiting for return from user.
But yes, I think it's fixed now.

**Comment by VivantSenior** [comment]
Hi,

my ConBee 2 still doesn't show battery % of Xiaomi Multisensor (WSDCGQ11LM).

Version: 2.05.70 / 25.10.2019
Firmware: 264A0700

Best,
Viv

**Comment by bcutter** [comment]
Same for me: I miss the battery information (!)

Phoscon:
![grafik](https://user-images.githubusercontent.com/13799156/105635420-fbd86180-5e62-11eb-800f-454307f3de59.png)

deCONZ:
![grafik](https://user-images.githubusercontent.com/13799156/105635431-101c5e80-5e63-11eb-96eb-eb083d8717c5.png)

But no battery level entity reported to Home Assistant.

ConBee 2 information:
![grafik](https://user-images.githubusercontent.com/13799156/105635478-41952a00-5e63-11eb-81c6-89747647a0bb.png)

According to deCONZ battery information exists, but no entity is generated:
![grafik](https://user-images.githubusercontent.com/13799156/105635546-abadcf00-5e63-11eb-9975-aa82ef1266e3.png)


I paired it once (immediately worked). **What can I do / check / try?**

**Comment by bcutter** [comment]
Update: It´s there now.

Phoscon:
![grafik](https://user-images.githubusercontent.com/13799156/105636284-fa5d6800-5e67-11eb-8592-a95a24c8fcd8.png)

deCONZ:
![grafik](https://user-images.githubusercontent.com/13799156/105636313-1c56ea80-5e68-11eb-890f-3183a75ca707.png)

And finally in Home Assistant:
![grafik](https://user-images.githubusercontent.com/13799156/105636279-f2052d00-5e67-11eb-8c0b-70caad7e975f.png)

I have no idea what triggered it, only things I did:
1) Wait (took ~ 45 minutes)
2) In deCONZ in "Cluster info" I selected the sensor and choose "read" in Attributes section

Will see on the next temperature sensors what does the trick, hope it´s the wait option... sorry for unnecessary noise in a closed issue.

Will put the "wait 1 to 3 hours after pairing" checkmark on my Xiaomi ZigBeed devices pairing checklist ;-)
