### ISSUE TITLE
IKEA-shutters gone after update to 2.05.75

### ISSUE THREAD

**Issue by Michaelnorge** [dresden-elektronik/deconz-rest-plugin#2558]
After update to v2.05.75 all my shutters from IKEA were gone from the Phoscon-App.
It was not possible to reconnect them, they didnt shown up again.

I made a downgrade to v2.05.74 - now everything works fine again.

**Comment by dwarf-rbi** [comment]
I have the same issue.. all blinds are gone, but the REMOTE open/close are now showing..

**Comment by manup** [comment]
Ah sorry our bad, since we're working on a dedicated window blinds page they are filtered on lights section (but are still available in the REST-API). Will be visible in the next version again until the new page officially launches.

**Comment by dwarf-rbi** [comment]
@manup Thanks for the answer. Are there already a timeframe for when the next version is coming? Got 7 more blinds to add soon.

**Comment by manup** [comment]
Should be online within the next 3 days, with only minor changes.

**Comment by ebaauw** [comment]
> since we're working on a dedicated window blinds page they are filtered on lights section

Are you using the right filter?  The `lumi.curtain` is still visible in Phoscon.  This device also has a `type` of `"Window covering device"`.  I think some-one added `"Window covering controller"` as well.

**Comment by Kane610** [comment]
@manup will that also bring proper pairing with the blinds to set up all bindings?

**Comment by dwarf-rbi** [comment]
And maybe even fixing the current cover position bug. All of my blinds are at 100% all the time.

**Comment by Kane610** [comment]
> And maybe even fixing the current cover position bug. All of my blinds are at 100% all the time.

That's what the binding does

**Comment by wettermann32** [comment]
same problem, ikea shutters are gone. anyhow there was also the problems with only a down arrow to controll the shutters in homeassistant. Does this fix belong to this also?

**Comment by dwarf-rbi** [comment]
@wettermann32 Im pretty sure the gray arrow is there because HA dosnt know the current position, and therefore thinks its all ways closed. So yes, this is does belong to this fix

**Comment by dwarf-rbi** [comment]
@manup Any news on the new update? My 11 blinds dosnt really work at the moment :-(

**Comment by llonca13** [comment]
Impossible to pair Fyrtur for days with this new version. After downgrade to v2.05.74, pairs and works again.

**Comment by StoricU** [comment]
Any news about next update?
Considering downgrading to .74

**Comment by wettermann32** [comment]
@llonca13
can you short describe how I can downgrade to 74?
Thanks Michael

**Comment by Michaelnorge** [comment]
> @llonca13
> can you short describe how I can downgrade to 74?
> Thanks Michael

Turn on "expert-mode" at the adapter site.
Press the invert "+" on the far right in the line where the adapter is.
Choose the right version.

**Comment by Zapfmeister** [comment]
Im also looking forward to the next release! :-)

**Comment by dwarf-rbi** [comment]
@Michaelnorge Is this in the deCONZ ui you are referering to?

**Comment by yabbah** [comment]
"Turn on "expert-mode" at the adapter site.", where do I found this?

**Comment by wettermann32** [comment]
@manup: any news about the next version?

**Comment by johnnykarlberg** [comment]
can someone please tell me how to downgrade in hassio without a snapshot?

**Comment by frenck** [comment]
@johnnykarlberg You can't downgrade it without a snapshot.

**Comment by johnnykarlberg** [comment]
Not even install a Fresh one with folder?

Den fre 1 maj 2020 17:19Franck Nijhof <notifications@github.com> skrev:

**Comment by stigvi** [comment]
> Should be online within the next 3 days, with only minor changes.

What happened?

**Comment by dwarfadmin** [comment]
Im not sure what happened @manup, Im still struggling with this current version

**Comment by johnnykarlberg** [comment]
Thank you

Den mån 4 maj 2020 10:21Dwarf Reg <notifications@github.com> skrev:

**Comment by stigvi** [comment]
Well, in these Corona times, you never know. I hope everything is well with manup and everyone else who is contributing and their families.

**Comment by monster400** [comment]
Hello

Any news? about next release?

**Comment by llonca13** [comment]
+1. Could you at least say whats the status of some of the Ikea issues with deconz and if your not able to support it further to look elsewhere.. I dont want to sound rude, but this is not some no-name off brand chinese product, I bet half of conbee/raspbee buyers have this blinds and it would be very nice to update us on the status of this problem, or give us any info on the timeframe when this issue can be looked at. Thanks!

**Comment by Michaelnorge** [comment]
I´am still on 74. 
I´am using Ikea shutters through the Ikea gateway and adapter and I´am happy with it so far.

**Comment by yabbah** [comment]
Im on 2.05.75 and my IKEA Fyrtur working for me. But Phoscon dont have support for the open/close switch in the switch editor. But you can just use automations in HA och Node-red to get it working. I used these steps:

1. create the group for the blind in Phoscon
2. Start search for a light
3. Remove the battery in the blind for 5 seconds
4. Hold both bottons on the blind until it stop pulse, and 3 more seconds after that. 
After some seconds you will see should see the blind in Phoscon and deCONZ gui.
Change to a proper name and assign to the created group in step 1.

To add the open/close you just search for a switch -> Other and press the switch reset button 4 times within some seconds.

**Comment by ebaauw** [comment]
The open/close remote can control the blinds directly, without the need for any automation.  Just add the blinds to the group associated with the remote.

**Comment by yabbah** [comment]
> The open/close remote can control the blinds directly, without the need for any automation. Just add the blinds to the group associated with the remote.

I wasnt able to add the switch to the group in Phoscon tho.

**Comment by Smanar** [comment]
@yabbah You don't need to add the switch to the group, but add the blinds to the group associated to the remote.

**Comment by dwarf-rbi** [comment]
@yabbah You can add the open/close in phoscon. I wasnt able to connect the open/close directly to the blind. 
![image](https://user-images.githubusercontent.com/54988285/81503524-51c0a580-92e4-11ea-9006-acb8b72a7b16.png)

**Comment by wettermann32** [comment]
deconz is not reporting the Position of the blinds. So I can only move it once down in hassio via the UI. 

It is now 2 months since manup said "within 3 days"… I hoped on more support using deconz Hardware. Has somebody experience with cc2531 and zigbee2mqtt?

**Comment by hwikene** [comment]
Try removing batteries for 2-3min and seeing that helps

**Comment by PexJensen** [comment]
@manup is this fixed in .76 ?

**Comment by stigvi** [comment]
They are listed as light in .76

**Comment by wettermann32** [comment]
Position of blinds is still not reported in .76. ALways 100%. You can Change the Position by Hand in hass via developertools-> Status. But after Restart you need to do this again.

**Comment by Mimiix** [comment]
@wettermann32 You need to redo the binding for this to report. Info on that is in discord, or wiki page.

I'll close this issue, as its resolved.

**Comment by maqf12** [comment]
Turn on "expert-mode" at the adapter site.
Press the invert "+" on the far right in the line where the adapter is.
Choose the right version.

... Can someone pls tell me where do i find this ?.. What is adapter site ? ,, is it "gateway" where i can se firmware etc.. if so, there is no "+"
