### ISSUE TITLE
26350500 - 2.05.75 - Cannot pair Philips HUE Dimmer

### ISSUE THREAD

**Issue by WhistleMaster** [dresden-elektronik/deconz-rest-plugin#2649]
Hi,

I'm using Deconz  v2.05.75 with Conbee I on firmware 26350500 with Docker (marthoc image). The Conbee is attached to a NUC with an USB extension cable.

I'm trying to add two Philips HUE Dimmer (4 buttons) but I can't pair them through the Phoscon App. 

I go to Switches -> Add new switch -> Philips -> Dimmer Switch.
I press on the Setup button and release when the dimmer light turns green. 
Then, the light on the dimmer turns off but the dimmer is not added on Phoscon.

If I go to Deconz interface with VNC, I can see that a new device appears, but nothing more:

<img width="290" alt="Screenshot 2020-04-04 at 10 08 07" src="https://user-images.githubusercontent.com/1544568/78422122-459a5600-765d-11ea-975b-384977e4def1.png">
<img width="325" alt="Screenshot 2020-04-04 at 10 08 20" src="https://user-images.githubusercontent.com/1544568/78422124-4632ec80-765d-11ea-884c-114f15681d25.png">
<img width="247" alt="Screenshot 2020-04-04 at 10 08 26" src="https://user-images.githubusercontent.com/1544568/78422125-47641980-765d-11ea-8c50-96618a45d790.png">

I tried to remove the battery from the dimmer, start again the pairing procedure, press on the 4 buttons to do a soft-reset, nothing helps.

Thanks for your help !

**Comment by ebaauw** [comment]
The 0x01 endpoint is not shown.  Looks like deCONZ didn't read the _Simple descriptor_ for that endpoint.  Could you try to _Read Node Descriptor_ and _Read Simple Descriptor(s)_ and see whether the first endpoint appears?  Make sure to press a button on the dimmer every seconds or so, to force it to be awake.  If that doesn't help reset the dimmer (hold the reset button for 10 seconds), and try to re-pair it.

**Comment by WhistleMaster** [comment]
I've seen that the devices were in the `zll.db` sqlite database with the "deleted" state (`deletedState`) in the `sensors` table and were also in the `devices`.

I shutdown Deconz, removed the entries from the tables, startup Deconz and tried to add the devices again.

I had to do what you suggested (_Read Node Descriptor and Read Simple Descriptor(s)_) and it worked.

I don't know if deleting the "deleted" devices from the database helped or not... @manup 

Thanks for your help !

**Comment by mat1990dj** [comment]
It seems what I have but with different devices
![image](https://user-images.githubusercontent.com/5220059/78666765-20654c00-78d8-11ea-8ba6-aaeb0a7436c7.png)
Should I delete from zll.db?

**Comment by WhistleMaster** [comment]
If you deleted the `zll.db`, you'll loose all your devices. You need to use `sqlite3` to delete only the rights entries.

**Comment by mat1990dj** [comment]
Yes, I deleted the entries from zll.db and then started deconz, the ghost devices are gone but if I try to pair them again they come again in this strange format without name and not pairing

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!

**Comment by sunshineautomate** [comment]
I'm still experiencing this issue! Can it be reopened please?

**Comment by Mimiix** [comment]
@sunshineautomate I rather have you post your issue on the forum. https://forum.phoscon.de :)
