### ISSUE TITLE
_TYZB02_keyjqthh TS0041

### ISSUE THREAD

**Issue by bsfaxi** [dresden-elektronik/deconz-rest-plugin#3042]
Hi,
I have bought the following Smart Switch and Remote/Wireless Switch that normally work with a Xiaomi GW.
Smart switch : https://fr.aliexpress.com/item/10000008539597.html?spm=a2g0s.9042311.0.0.76326c37upJGCV
Wireless switch : https://fr.aliexpress.com/item/10000065424854.html?spm=a2g0s.9042311.0.0.27426c37Xn8EwX
I have succeded to pair them with Phoscon using a Raspbee. The Smart Switch works perfectly and is recognized as a light. So, it's okay to turn on/off the light. However, the Wireless switch is also recognized as a light, and thus cannot be used as a scene button.
So, is it possible to add the support of this device please?
Below are the required information. Are there any further details that are needed?
![image](https://user-images.githubusercontent.com/23717629/87419022-08861e00-c5d3-11ea-823e-cf6ef4cbd0b1.png)
![image](https://user-images.githubusercontent.com/23717629/87419042-12a81c80-c5d3-11ea-89c1-17de375546cd.png)

Thanks in advance for your precious help.

**Comment by Smanar** [comment]
I m sorry for you, but I think you have one of this boring tuya device.
I think too you miss a cluster in your capture, but not your fault, it from the device (there is another device with the same problem), can you check (on deconz) if on the wired one you haven't a cluster EF00 ?

**Comment by bsfaxi** [comment]
> I m sorry for you, but I think you have one of this boring tuya device.
> I think too you miss a cluster in your capture, but not your fault, it from the device (there is another device with the same problem), can you check (on deconz) if on the wired one you haven't a cluster EF00 ?
> 
> BTW, you haven't something to sniff zigbee device ? I m searching why it s the second device with this problem.

Hi Smanar,
Thanks for time to get an eye on this. I'm quite newbee to this. :)
Indeed it's a boring Tuya device, but with cool design! :)
I just need to recognize this wireless switch as a scene button (1 press, double press or a long press and release), or as a 2 ways switch with an automation. So, I can't if it's recognized as a light.
Please find below other screenshots including the smart switch (the wired one) and the wireless one.
What other info do you need?

![image](https://user-images.githubusercontent.com/23717629/87677927-99e3c480-c77a-11ea-9295-048646cab6b9.png)
![image](https://user-images.githubusercontent.com/23717629/87677957-a405c300-c77a-11ea-989b-64a24fa83f4e.png)

Thanks.

**Comment by Smanar** [comment]
For the moment I need help, but a solution ^^.
To make it clear, I m sure you miss a cluster, first because I have other device with same bug, and second because you only have a on/off cluster, so only with this cluster you can't make simple/double/long click.

I can add your device in whitelist for you try the tuya branch, but I already have some problem on other tuya device.

BTW I need the manufacture code, you can find it on "Node info" panel.

**Comment by bsfaxi** [comment]
Here you go.

For the Wireless :
![image](https://user-images.githubusercontent.com/23717629/87699636-6febcb80-c795-11ea-9a58-d97392dd33b7.png)

For the Wired :
![image](https://user-images.githubusercontent.com/23717629/87699692-84c85f00-c795-11ea-876b-048887a2bd25.png)

**Comment by Smanar** [comment]
Ok so, you try the tuya code.

On the compilation procedure, just chnage step 1 by

`git clone --branch tuya https://github.com/Smanar/deconz-rest-plugin.git`

Don't be optimistic, nothing magic, just you device will appear in API, and you will see some debug line when you use it.

**Comment by Smanar** [comment]
Hello, have you tried your device with last code ?
If you can include it, I need you run deconz in debug mode and debug line starting with "Tuya debug 4:" that will apper when you use it.

**Comment by Smanar** [comment]
We have finished the first tuya device https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3024
So if you can try the same code and check for "Tuya debug 4" in log when using the switch ?

**Comment by bsfaxi** [comment]
Hi Smanar,
Sorry for the late response.
I'll give a try this weekend, and get back to you with feedback.
Thanks a lot again. :)

**Comment by Smanar** [comment]
Have you got some time to make tries ?

**Comment by cobirnm** [comment]
I have one of these switches. How can I help?
At the moment I can add it but it is added as a light. This should be a switch.

**Comment by Smanar** [comment]
Sure, it s possible if your device have exactly the same manufacture name ?

But ATM the tuya code is in waiting list, so not a lot change ATM.

Wich one version are you using ? Do you know how to compile the code to make tries on your side ? have you a real Unix machine ?

**Comment by cobirnm** [comment]
> Sure, it s possible if your device have exactly the same manufacture name ?
> 
> But ATM the tuya code is in waiting list, so not a lot change ATM.
> 
> Wich one version are you using ? Do you know how to compile the code to make tries on your side ? have you a real Unix machine ?

Well to answer you I have a raspberry pi, and probably no i can't copile the code.
It's a pity because tuya devices have great quality/price!

**Comment by cobirnm** [comment]
> Sure, it s possible if your device have exactly the same manufacture name ?
> 
> But ATM the tuya code is in waiting list, so not a lot change ATM.
> 
> Wich one version are you using ? Do you know how to compile the code to make tries on your side ? have you a real Unix machine ?

Well to answer you I have a raspberry pi, and probably no i can't copile the code.
It's a pity because tuya devices have great quality/price!

Regarding the device yes it's exacly the same manufacture name. Regarding deconz I'm using version 2.05.82

**Comment by Smanar** [comment]
A raspberry is good, but I suppose you have Hassio ?

**Comment by bsfaxi** [comment]
Hello again,
I finally got a CC2531, which I patched with the ZBoss sniffer firmware.
In Wireshark, I can see the following command "0xfd" :
![image](https://user-images.githubusercontent.com/23717629/94926135-95e55a00-04c0-11eb-998b-e0e3c088c737.png)
I hope it helps.

**Comment by Smanar** [comment]
We already have this command now > https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/button_maps.json#L573

The code have moved since the last time, and the tuya PR is validated.

Give me time to update with last deconz version, I will add the switch again for test.

**Comment by bsfaxi** [comment]
Cool. :-)
I can see Tuya3gangMap.
Is it OK to handle also the 2 other Tuya Wireless Switches with 1 and 2 gangs?

**Comment by Smanar** [comment]
Yep I think the same code will work for all gangs, but there is a problem.
The vendor manu number is on white list so the device is reconized as light instead of sensor ...

First try
`git clone --branch tuya https://github.com/Smanar/deconz-rest-plugin.git`

This code will prevent the device will be visible as light.

**Comment by cobirnm** [comment]
> A raspberry is good, but I suppose you have Hassio ?
> 
> And yes there is so much tuya device every week, realy active manufacture.

No I'm on Raspbian

**Comment by cobirnm** [comment]
@Smanar , my model is TS0012 (2 gang) do you think your code will work for me?

**Comment by Smanar** [comment]
@cobirnm 
I need to add it in the whitelist, I need
- manufacture number
- manufacture name
- the mac adresss (the 6 firsts number)
- if the device is reconized as router or not.

But yes I think it will use the same code

**Comment by bsfaxi** [comment]
I compiled the latest code successfully.
The wireless switch appears in Deconz, but doesn't show up in the Phoscon App, neither in lights and in switches.

**Comment by bsfaxi** [comment]
I have also the Wireless switch with 3 gangs.
I'll test it, and provide details.

**Comment by Smanar** [comment]
Yep can be normal it will be invisible on phoscon.
Need to check in the api or in your third app.

**Comment by bsfaxi** [comment]
In Home Assistant, the device appears in the integration, but not the entity switch which can be controlled.

![image](https://user-images.githubusercontent.com/23717629/94990429-52e8bc80-057c-11eb-82dd-8d1002c63867.png)

![image](https://user-images.githubusercontent.com/23717629/94990436-66942300-057c-11eb-9207-06c1a45bd50b.png)

**Comment by bsfaxi** [comment]
For the Wireless 2 gangs, I have the following:

![image](https://user-images.githubusercontent.com/23717629/94990501-f20db400-057c-11eb-8a55-eb9fc0b1cfd8.png)

![image](https://user-images.githubusercontent.com/23717629/94990517-110c4600-057d-11eb-8b65-d07540e72476.png)

**Comment by bsfaxi** [comment]
For the Wireless 2 gangs, it doesn't even appear in Home Assistant. It only appears in Deconz.

**Comment by bsfaxi** [comment]
For the Wireless 3 gangs, I have the following:

![image](https://user-images.githubusercontent.com/23717629/94990660-2fbf0c80-057e-11eb-9a6c-439ea7af3934.png)

![image](https://user-images.githubusercontent.com/23717629/94990682-4d8c7180-057e-11eb-9c75-b9df83800f21.png)

**Comment by bsfaxi** [comment]
Same thing for this Wireless switch: it doesn't even appear in Home Assistant. It only appears in Deconz.

**Comment by Smanar** [comment]
They are all wireless ?

I have added the 2 other devices too > https://github.com/Smanar/deconz-rest-plugin/commit/ae77bcacaa413bbefdf5e8899f4d4a10d6e08e62

But you need to delete the one you can see, he is in "light" section, the good one will be in "sensor" section, you need to re - include them too.

**Comment by bsfaxi** [comment]
It's recognized by the Phoscon App as a Sensor, but doesn't appear in the list of Sensors.
In Home Assistant, the device appears but not the sensor entity.

**Comment by cobirnm** [comment]
> yes I think it will
Please find the details below:

![image](https://user-images.githubusercontent.com/45829329/95009886-289b0b80-061d-11eb-8c05-45a36c12c1dd.png)

![image](https://user-images.githubusercontent.com/45829329/95009898-423c5300-061d-11eb-84b8-ddc1019b9d8f.png)
![image](https://user-images.githubusercontent.com/45829329/95009906-4ff1d880-061d-11eb-9a92-54ff03b7042b.png)
![image](https://user-images.githubusercontent.com/45829329/95009921-67c95c80-061d-11eb-834f-664c8894130c.png)
![image](https://user-images.githubusercontent.com/45829329/95009934-816aa400-061d-11eb-956c-d22c2296c553.png)
![image](https://user-images.githubusercontent.com/45829329/95009941-8deefc80-061d-11eb-878f-f305fb9bc9f3.png)

**Comment by Smanar** [comment]
Have added the @cobirnm switch, if you can try too ?

>It's recognized by the Phoscon App as a Sensor, but doesn't appear in the list of Sensors.
In Home Assistant, the device appears but not the sensor entity.

He is still in "light" section ?
Can you show the device JSON ? you can find it in your third app or using an url like this `http://IP:PORT/api/API_KEY/sensors`

IP and PORT > same than for phoscon.

**Comment by bsfaxi** [comment]
> He is still in "light" section ?
>>
Not in lights either. Nowhere in Phoscon app. Only in Deconz.


> It mean you have a success message during pairing ?
>>
Yes, the Phoscon App show success paring with the device as a sensor. But then, it doesn't show up in the list.


> Can you show the device JSON ? you can find it in your third app or using an url like this `http://IP:PORT/api/API_KEY/sensors`
>>
{"1":{"config":{"configured":true,"on":true,"sunriseoffset":30,"sunsetoffset":-30},"etag":"42d221e47b288d20c94bc52f251bb1ef","manufacturername":"Philips","modelid":"PHDL00","name":"Daylight","state":{"dark":false,"daylight":true,"lastupdated":"2020-10-04T10:24:38.042","status":160,"sunrise":"2020-10-04T05:56:01","sunset":"2020-10-04T17:24:54"},"swversion":"1.0","type":"Daylight","uniqueid":"00:21:2e:ff:ff:05:31:b7-01"},
"2":{"config":{"battery":null,"on":true,"reachable":false},"ep":1,"etag":"42d221e47b288d20c94bc52f251bb1ef","lastseen":null,"manufacturername":"_TYZB02_keyjqthh","mode":1,"modelid":"TS0041","name":"TS0041","state":{"buttonevent":null,"lastupdated":"none"},"type":"ZHASwitch","uniqueid":"ec:1b:bd:ff:fe:76:d7:64-01-0006"}}

**Comment by Smanar** [comment]
He is here ^^

`"2":{"config":{"battery":null,"on":true,"reachable":false},"ep":1,"etag":"42d221e47b288d20c94bc52f251bb1ef","lastseen":null,"manufacturername":"_TYZB02_keyjqthh","mode":1,"modelid":"TS0041","name":"TS0041","state":{"buttonevent":null,"lastupdated":"none"},"type":"ZHASwitch","uniqueid":"ec:1b:bd:ff:fe:76:d7:64-01-0006"}}`

Try to use it and look if the field "buttonevent":null change.

**Comment by bsfaxi** [comment]
Yep, I saw it. :)

The field buttonevent doesn't change at all.
In HomeAssistant, the sensor entity for this device doesn't show up.

**Comment by Smanar** [comment]
I have updated the code to make a bind/attribute reporting for this device, if you can make another try ?

But I don't understand for HA, you have checked in all section ? Don't need a "synchronisation" ?

**Comment by bsfaxi** [comment]
I will give it another try.

In HA, the update is automatically done. I even reinstalled the integration to be sure.

**Comment by bsfaxi** [comment]
A little better. :) 
Now, I have the battery level. But, I still have this in the API {"buttonevent":null,"lastupdated":"none"}.

![image](https://user-images.githubusercontent.com/23717629/95016636-7e3eda80-0654-11eb-9eec-1c9cec504201.png)

**Comment by Smanar** [comment]
Ha yep haven't added the battery yet.
But it s strange you haven't value ...

Do you know how to enable deconz log on HA ?
When you press the button you will have some debug line, for exemple

>[INFO] - No button handler for: ..............

**Comment by bsfaxi** [comment]
Yes, I have no value for the battery.

I have added this to the configuration.yaml of HA:
logger:
  default: info
  logs:
    pydeconz: debug
    homeassistant.components.deconz: debug

This is an extract from the logs concerning the device TS0041:
...
             '2': {'config': {'battery': 0, 'on': True, 'reachable': True},
                   'ep': 1,
                   'etag': '4b38ddc6e1fe3ef55b99aacbfbc54196',
                   'lastseen': '2020-10-04T13:24Z',
                   'manufacturername': '_TYZB02_keyjqthh',
                   'mode': 1,
                   'modelid': 'TS0041',
                   'name': 'TS0041',
                   'state': {'buttonevent': None, 'lastupdated': 'none'},
                   'type': 'ZHASwitch',
                   'uniqueid': 'ec:1b:bd:ff:fe:76:d7:64-01-0006'}}}

2020-10-04 17:33:54 DEBUG (MainThread) [pydeconz.deconzdevice] TS0041 created as
{'config': {'battery': 0, 'on': True, 'reachable': True},
 'ep': 1,
 'etag': '4b38ddc6e1fe3ef55b99aacbfbc54196',
 'lastseen': '2020-10-04T13:24Z',
 'manufacturername': '_TYZB02_keyjqthh',
 'mode': 1,
 'modelid': 'TS0041',
 'name': 'TS0041',
 'state': {'buttonevent': None, 'lastupdated': 'none'},
 'type': 'ZHASwitch',
 'uniqueid': 'ec:1b:bd:ff:fe:76:d7:64-01-0006'}

No events are logged when I press the button.

**Comment by Smanar** [comment]
Don't make mistake beetween deconz log and the HA plugin log.
A deconz log look like 

> 9:43:24:977 06 unsupported index (data type 0x20)
> 19:43:32:720 0x00158D000171E9E0 error APSDE-DATA.confirm: 0xF0 on task
> 19:43:32:720 APS-DATA.confirm id: 76 status: transaction expired (8 seconds)
> 19:45:48:271 0x00178801029AA1D7 error APSDE-DATA.confirm: 0xE9 on task
> 19:45:56:693 button 1002 Normal release
> 19:45:56:695 ZCL attribute report 0x00158D00018B4A84 for cluster 0x0006, ep 0x01
> 19:45:57:207 no button map for: lumi.weather ep: 0x01 cl: 0x0402 cmd: 0x0A pl[0]: 000
> 19:45:59:300 0x00178801021D61FE force poll (2)
> 19:46:00:357 0x00178801029AA1D7 error APSDE-DATA.confirm: 0xA7 on task

**Comment by bsfaxi** [comment]
Here you go:

In the beginning of the file:
11:43:48:885 verify 0xec1bbdfffe76d764 is child node after 809128 s
11:43:48:885 Node data 0xec1bbdfffe76d764 profileId: 0x0104, clusterId: 0x0000
11:43:48:885 SensorNode id: 2 (TS0041) available
11:43:48:885 Update Sensor 0xEC1BBDFFFE76D764 Basic Cluster
**11:43:48:885 [INFO] - No button map for: TS0041 endpoint: 0x01 cluster: 0x0000 command: 0x0A payload[0]: 001**
11:43:48:885 ZCL attribute report 0xEC1BBDFFFE76D764 for cluster: 0x0000, ep: 0x01, frame control: 0x18, mfcode: 0x0000
11:43:48:885    payload: 01002044
11:43:48:887 Websocket 192.168.0.29:51827 send message: {"config":{"on":true,"reachable":true},"e":"changed","id":"2","r":"sensors","t":"event","uniqueid":"ec:1b:bd:ff:fe:76:d7:64-01-0006"} (ret = 5695152)
11:43:48:888 Websocket 192.168.0.79:44786 send message: {"config":{"on":true,"reachable":true},"e":"changed","id":"2","r":"sensors","t":"event","uniqueid":"ec:1b:bd:ff:fe:76:d7:64-01-0006"} (ret = 5695152)

A little further, when clicked on the button:
11:44:03:818 Node 0xEC1BBDFFFE79B4C8 is known by 0 neighbors, last seen 0 s
11:44:04:154 sql exec SELECT conf FROM zbconf ORDER BY rowid desc limit 1
11:44:04:155 Wait 5s till query finished
11:44:04:298 Node 0xBC33ACFFFE17054E is known by 1 neighbors, last seen 6 s
11:44:04:417 MAC Poll 0x02 0x1A8F
11:44:04:444 APS-DATA.indication from child 0x1A8F
**11:44:04:444 [INFO] - No button map for: TS0041 endpoint: 0x01 cluster: 0x0006 command: 0xFD payload[0]: 000**
11:44:04:557 HTTP client hdr detected:
GET /api/406/config/wifi/ HTTP/1.1^M
Host: 127.0.0.1^M
User-Agent: curl/7.64.0^M
Accept: */*^M

**Comment by Smanar** [comment]
Ok I think I have understand, on last (and future version), you need to have a file called button_maps.json.
This file is editable with a text editor (json format) and contain all values for switchs.

So to test last versions you need to copy this file https://github.com/Smanar/deconz-rest-plugin/blob/tuya/button_maps.json in a deconz folder (/usr/share/deCONZ/devices/button_maps.json)

> 
> Outsource button maps to external JSON file @SwoopX (#3127):
> All available button maps have been outsourced to an external JSON file named button_maps.json, which must reside in the same directory as the deCONZ database zll.db. The purpose is to speed up integration of new switches as users can now create it theirselves (given that some appropriate guidance is provided).

**Comment by bsfaxi** [comment]
Hi @Smanar ,
I think there still a problem with that file.
Here what I have in the log in my last test 10mn ago (I don't know why, in the log, the timestamp starts with my local time CEST and then switches to GMT):
...
08:47:38:275 [INFO] - Found file containing button maps. Parsing data...
08:47:38:280 [ERROR] - Error: illegal value at offset: 6 (in characters)
08:47:38:280 [ERROR] - No object named 'buttons' found in JSON file. Skip to load button maps.
...

**Comment by bsfaxi** [comment]
it's better, Now I have this:
12:57:40:038 [INFO] - Found file containing button maps. Parsing data...
12:57:40:041 [ERROR] - Button map 'instaRemoteMap' in JSON file has no assigned ModelIDs. Skip loading button map...
12:57:40:041 [ERROR] - Button map 'sunricherCCTMap' in JSON file has no assigned ModelIDs. Skip loading button map...
**12:57:40:047 [INFO] - Button maps loaded.**
...
**12:59:29:080 {"2":{"name":"TS0041"},"lastscan":"active"}**
12:59:29:267 Node 0xBC33ACFFFE17054E is known by 1 neighbors, last seen 38 s
12:59:29:430 ZCL read cluster: 0x0000, attribute: 0x0000
12:59:29:430 ZCL read cluster: 0x0000, attribute: 0x0001
12:59:29:430 ZCL read cluster: 0x0000, attribute: 0x0002
12:59:29:430 ZCL read cluster: 0x0000, attribute: 0x0003
12:59:29:430 ZCL cmd-req nwk: 0xEED7, profile: 0x0104, cluster: 0x0000 cmd: 0x00
12:59:29:430 ZCL read cluster: 0x0000, attribute: 0x0004
12:59:29:430 ZCL cmd-req nwk: 0xEED7, profile: 0x0104, cluster: 0x0000 cmd: 0x00
12:59:29:430 ZCL read cluster: 0x0000, attribute: 0x0005
12:59:29:430 ZCL cmd-req nwk: 0xEED7, profile: 0x0104, cluster: 0x0000 cmd: 0x00
12:59:29:430 ZCL read cluster: 0x0000, attribute: 0x0006
12:59:29:430 ZCL cmd-req nwk: 0xEED7, profile: 0x0104, cluster: 0x0000 cmd: 0x00
12:59:29:431 ZCL read cluster: 0x0000, attribute: 0x0007
12:59:29:431 ZCL read cluster: 0x0000, attribute: 0x0008
12:59:29:431 ZCL read cluster: 0x0000, attribute: 0x0009
12:59:29:431 ZCL read cluster: 0x0000, attribute: 0x000A
12:59:29:431 ZCL cmd-req nwk: 0xEED7, profile: 0x0104, cluster: 0x0000 cmd: 0x00
...
**12:59:34:703 [INFO] - Button 1002 B1 short**
12:59:34:758 Websocket 192.168.0.29:63775 send message: {"e":"changed","id":"2","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2020-10-06T12:59:34.703"},"t":"event","uniqueid":"ec:1b:bd:ff:fe:76:d7:64-01-0006"} (ret = -1091027600)
12:59:34:760 discard sensor state push for 2: state/lastupdated (already pushed)
...
**12:59:41:776 [INFO] - Button 1004 B1 double**
12:59:41:778 Websocket 192.168.0.29:63775 send message: {"e":"changed","id":"2","r":"sensors","state":{"buttonevent":1004,"lastupdated":"2020-10-06T12:59:41.775"},"t":"event","uniqueid":"ec:1b:bd:ff:fe:76:d7:64-01-0006"} (ret = -1091027600)
12:59:41:779 discard sensor state push for 2: state/lastupdated (already pushed)
...
12:59:43:210 DB sql exec REPLACE INTO sensors (sid, name, type, modelid, manufacturername, uniqueid, swversion, state, config, fingerprint, deletedState, mode) VALUES ('2', 'TS0041', 'ZHASwitch', 'TS0041', '_TYZB02_keyjqthh', 'ec:1b:bd:ff:fe:76:d7:64-01-0006', '', '{"buttonevent":1004,"lastupdated":"2020-10-06T12:59:41.775"}', '{"battery":null,"on":true,"reachable":true}', '{"d":0,"ep":1,"in":[0,1,6],"p":260}', 'normal', '1')
...

So, it seems to be taken into account.
However, only the device info is present in Home Assistant not the entity, even with doing the deconz integration from scratch.
![image](https://user-images.githubusercontent.com/23717629/95207247-f4277b00-07e7-11eb-96ea-0f9573790c31.png)

**Comment by bsfaxi** [comment]
when I do curl http://192.168.0.79/api/79971660D3/sensors, I can see the 3 button events 1002 (single click), 1004 (double click) and 1003 (long press).
{"1":{"config":{"configured":true,"on":true,"sunriseoffset":30,"sunsetoffset":-30},"etag":"98b56b3ab1212f881fbdfef20ec3c66d","manufacturername":"Philips","modelid":"PHDL00","name":"Daylight","state":{"dark":false,"daylight":true,"lastupdated":"2020-10-06T13:16:41.530","status":170,"sunrise":"2020-10-06T05:58:58","sunset":"2020-10-06T17:20:44"},"swversion":"1.0","type":"Daylight","uniqueid":"00:21:2e:ff:ff:05:31:b7-01"},"2":{"config":{"battery":null,"on":true,"reachable":true},"ep":1,"etag":"709e55c52a891b0f14c67c45d012366b","lastseen":"2020-10-06T13:36Z","manufacturername":"_TYZB02_keyjqthh","mode":1,"modelid":"TS0041","name":"TS0041","state":{"buttonevent":1003,"lastupdated":"2020-10-06T13:36:21.943"},"type":"ZHASwitch","uniqueid":"ec:1b:bd:ff:fe:76:d7:64-01-0006"}}

**Comment by cobirnm** [comment]
on quick question. I have passed the last 2 days trying to compile the branch in to a docker image. (whitout success). Are you using docker to test the image or testing it on the "normal" system?

I'm trying not to mess my configuration.

**Comment by Smanar** [comment]
Hello

@bsfaxi  what you have done to solve
```
08:47:38:275 [INFO] - Found file containing button maps. Parsing data...
08:47:38:280 [ERROR] - Error: illegal value at offset: 6 (in characters)
08:47:38:280 [ERROR] - No object named 'buttons' found in JSON file. Skip to load button maps.
```

ATM I m locked, the compilation don't work on my machine, so I can make modification , but impossible for me to test them.

For the device that is badly displayed in HA, I think it s better to ask in HA plugin forum/github with showing the JSON

```
"2":{
   "config":{
      "battery":null,
      "on":true,
      "reachable":true
   },
   "ep":1,
   "etag":"709e55c52a891b0f14c67c45d012366b",
   "lastseen":"2020-10-06T13:36Z",
   "manufacturername":"_TYZB02_keyjqthh",
   "mode":1,
   "modelid":"TS0041",
   "name":"TS0041",
   "state":{
      "buttonevent":1003,
      "lastupdated":"2020-10-06T13:36:21.943"
   },
   "type":"ZHASwitch",
   "uniqueid":"ec:1b:bd:ff:fe:76:d7:64-01-0006"
}
```

@cobirnm you need a normal OS, It s possible on a VM with a full OS, but I realy don't know if it s possible on docker.

Next step the battery.

**Comment by bsfaxi** [comment]
> One quick question. I have passed the last 2 days trying to compile the branch in to a docker image. (whitout success). Are you using docker to test the image or testing it on the "normal" system?
> 
> I'm trying not to mess my configuration.

Hi,
For my production, I'm using HassOS on Raspberry pie 4. It's using Docker underneath...
I searched a while, but it's not obvious to do all the dev staff with this configuration.

But, for the DEV (the same Raspberry with another SD card), I installed Raspbian and then the Deconz and Home Assistant packages to be able to build and test, and also to patch the Raspbee ii with the latest firmware.

**Comment by bsfaxi** [comment]
> what you have done to solve
I simply was downloading the json with wget. :)
And then, I saw that the file exists already in the deconz-rest-plugin directory which was downloaded with the "git clone" command.

> ATM I m locked, the compilation don't work on my machine, so I can make modification , but impossible for me to test them.
Let me know when the code is modified to make the required tests. Let's go for the Battery... :)

**Comment by bsfaxi** [comment]
> For the device that is badly displayed in HA, I think it s better to ask in HA plugin forum/github with showing the JSON

I will open an issue for that.
But, do you know why it's not displayed also in the Phoscon App as a sensor?

**Comment by Smanar** [comment]
Lot of devices are not displayed in phoscon, this app use white/blacklist, for phoscon Im  not surprised, but for HA I don't understand `"type":"ZHASwitch",` most of third app just use that, and the value is correct.

BTW for battery I have forget something can you take a look on deconz cluster 0x0001 "power configuration" wich one attribute is used for battery ? 0x0020 or 0x0021 ?

**Comment by bsfaxi** [comment]
> Ok , i have found the capture on previous posts. But "battery percent remain" = 200 ??? WTF

Maybe it's normal, since the device has 2 batteries.


> Hu, I have some problem with battery ^^, it seem all the code is already in place, you don't have something about cluster 0x0001 in your log ?

For @cobirnm the % is at 200%. For me, it's always at 0% !
I will try with another one.

I can see these lines in the code. No errors.
08:25:28:842 0xEC1BBDFFFE76D764: added ZCL value 0x01/0x0001/0x0021
...
08:26:54:078 ZCL got data for node=0xC1E4, cl=0x0001, at=0x0021, status=0x00, type=0x20
08:26:54:079 Node data 0xec1bbdfffe76d764 profileId: 0x0104, clusterId: 0x0001
08:26:54:079 0xEC1BBDFFFE76D764: update ZCL value 0x01/0x0001/0x0021 after 0 s
08:26:54:120 discard sensor config push for config/battery (already pushed)
...
In Home Assistant too:
![image](https://user-images.githubusercontent.com/23717629/95311206-98afc880-088d-11eb-80f7-fbb18027edb4.png)

**Comment by bsfaxi** [comment]
I have tested with another wireless switch which has the same manufacturer name as @cobirnm's one: "_TZ3400_keyjqthh".

In deCONZ, the value is 200%.
![image](https://user-images.githubusercontent.com/23717629/95313955-00b3de00-0891-11eb-9224-3f8792263428.png)

In Home Assistant and APIs, the value is correct: 100%.
"3":{"config":{"**battery":100**,"on":true,"reachable":true},"ep":1,"etag":"1785727fefac4f06861bce9f00d40f4a","lastseen":"2020-10-07T09:29Z","manufacturername":"_TZ3400_keyjqthh","mode":1,"modelid":"TS0041","name":"TS0041 (2)","state":{"buttonevent":1004,"lastupdated":"2020-10-07T09:29:40.286"},"type":"ZHASwitch","uniqueid":"ec:1b:bd:ff:fe:87:1e:04-01-0006"}}
![image](https://user-images.githubusercontent.com/23717629/95313661-ab77cc80-0890-11eb-84ef-8f1fc841e25d.png)

**Comment by bsfaxi** [comment]
FYI, I have created an issue for the "Button Event" entity not been created in HA here https://github.com/home-assistant/core/issues/41405.

**Comment by Smanar** [comment]
Nice, I m curious for HA, I don't know at all if they use white/blacklist (I think not)

For the battery still a mystery, I have compared the working device and the not working, exactly the same code, I don't see why 1 is working and not the other ....

And the code receive value
>08:26:54:078 ZCL got data for node=0xC1E4, cl=0x0001, at=0x0021, status=0x00, type=0x20

For the 200 value I think now it s normal, the code make a division by 2 with the value.

**Comment by bsfaxi** [comment]
@Smanar 
I've done the test again. Not found the line with "Battery debug X"!
With the new code, I don't see anymore the button events...

Concerning HA, the integration works perfectly. I was not searching in the right place. The button generates an event and don't create an entity! :)

**Comment by Smanar** [comment]
You have only compiled the code (no change on json file ?)
Because the only change there is was some debug line added > https://github.com/Smanar/deconz-rest-plugin/commit/61ad1374c8e8bdfa4321e53dfb50d3b1ba97da12
Can't change the working mode.

Check to see if you are on the good branch

```
cd deconz-rest-plugin
git branch
```

**Comment by bsfaxi** [comment]
No change on json file.
I only recompiled the your previous commit:
git clone --branch tuya https://github.com/Smanar/deconz-rest-plugin.git
git checkout -b bilel f0fc8afe54a8863ef62f07332c2a1cfbfcc3950d
With this plugin version, the button events worked, not with your last change.
I will retry later if you want.


> cd deconz-rest-plugin
> git branch
* bilel
  tuya

**Comment by bsfaxi** [comment]
This is weired.
Now the button events are working again with your last code, and I have the following lines:
...
09:31:02:268 Node data 0xec1bbdfffe76d764 profileId: 0x0104, clusterId: 0x0000
09:31:02:268 Battery debug 1
09:31:02:268 Battery debug 2
09:31:02:268 Update Sensor 0xEC1BBDFFFE76D764 Basic Cluster
...
09:31:43:697 Node data 0xec1bbdfffe76d764 profileId: 0x0104, clusterId: 0x0001
09:31:43:697 Battery debug 1
09:31:43:697 Battery debug 2
09:31:43:697 Battery debug 3
09:31:43:697 0xEC1BBDFFFE76D764: added ZCL value 0x01/0x0001/0x0021
09:31:43:697 Battery debug 4
...

Just for your information, We still have errors with button map json file
09:30:17:243 [ERROR] - Button map 'instaRemoteMap' in JSON file has no assigned ModelIDs. Skip loading button map...
09:30:17:243 [ERROR] - Button map 'sunricherCCTMap' in JSON file has no assigned ModelIDs. Skip loading button map...
09:30:17:250 [INFO] - Button maps loaded.

**Comment by Smanar** [comment]
??? what is the "bilel" branch ? how are you find this name ?

For button map, IDK, I haven't modified this part, will say that to swoop, perhaps he know better
edit :
ok, so it s normal from him

For our problem, I realy don't understand, id k if you have looked the code ? "Battery debug 4" is exactly on battery code. All is fine.

A last try, sorry : https://github.com/Smanar/deconz-rest-plugin/commit/3a532a1f250dedc12a3757cf81df15d6e153c203

This debug line  will disaply direclty the read value

**Comment by Smanar** [comment]
BTW if you haven't time to test the code, I will make the PR without the battery, will finish the code later.

The time limit for PR is close ^^, but I can let he PR open

**Comment by bsfaxi** [comment]
Hi @Smanar ,
Just give few minutes to make the test. :)

**Comment by bsfaxi** [comment]
Is this what you're expecting ? 
BTW, you should submit the PR. My wireless switch could be somehow broken. I will only use it for tests. For my production, I'll use the same as @cobirnm's ones.

12:34:11:249 MAC Poll 0x02 0x86CC
12:34:11:314 ZCL read cluster: 0x0001, attribute: 0x0000
12:34:11:314 ZCL read cluster: 0x0001, attribute: 0x0001
12:34:11:314 ZCL read cluster: 0x0001, attribute: 0x0010
12:34:11:314 ZCL read cluster: 0x0001, attribute: 0x0011
12:34:11:314 ZCL cmd-req nwk: 0x86CC, profile: 0x0104, cluster: 0x0001 cmd: 0x00
12:34:11:314 ZCL read cluster: 0x0001, attribute: 0x0012
12:34:11:314 ZCL read cluster: 0x0001, attribute: 0x0013
12:34:11:314 ZCL read cluster: 0x0001, attribute: 0x0020
12:34:11:314 ZCL read cluster: 0x0001, attribute: 0x0021
12:34:11:314 ZCL cmd-req nwk: 0x86CC, profile: 0x0104, cluster: 0x0001 cmd: 0x00
12:34:11:314 ZCL read cluster: 0x0001, attribute: 0x0030
12:34:11:314 ZCL cmd-req nwk: 0x86CC, profile: 0x0104, cluster: 0x0001 cmd: 0x00
12:34:11:315 ZCL read cluster: 0x0001, attribute: 0x0031
12:34:11:315 ZCL read cluster: 0x0001, attribute: 0x0032
12:34:11:315 ZCL read cluster: 0x0001, attribute: 0x0033
12:34:11:315 ZCL read cluster: 0x0001, attribute: 0x0034
12:34:11:315 ZCL cmd-req nwk: 0x86CC, profile: 0x0104, cluster: 0x0001 cmd: 0x00
12:34:11:315 ZCL read cluster: 0x0001, attribute: 0x0035
12:34:11:315 ZCL read cluster: 0x0001, attribute: 0x0036
12:34:11:315 ZCL read cluster: 0x0001, attribute: 0x003E
12:34:11:315 ZCL cmd-req nwk: 0x86CC, profile: 0x0104, cluster: 0x0001 cmd: 0x00
12:34:11:413 Node 0xEC1BBDFFFE76D764 is known by 1 neighbors, last seen 0 s

**Comment by Smanar** [comment]
No more log with 
> 09:31:43:697 Battery debug 1 
?

**Comment by bsfaxi** [comment]
The debug line is still there, but nothing underneath (no value displayed with this device!):
12:57:45:459 Battery debug 1
12:57:45:908 Node 0xEC1BBDFFFE76D764 is known by 1 neighbors, last seen 4 s

Don't worry about this. :)

**Comment by Smanar** [comment]
Do you have the n 5 and the n 6 ? (the n 6 have a value too) ?

**Comment by bsfaxi** [comment]
I have repaired the wireless switch (0xEC1BBDFFFE871E04) with the same as the Cobirnm's one.
WIth this one, I have the following lines. Is it what you're searching for?
13:34:07:249 ZCL got data for node=0x1825, cl=0x0000, at=0x4000, status=0x86, type=0x00
13:34:07:249 Node data 0xec1bbdfffe871e04 profileId: 0x0104, clusterId: 0x0000
13:34:07:250 Battery debug 1
13:34:07:250 Battery debug 2
13:34:07:250 Update Sensor 0xEC1BBDFFFE871E04 Basic Cluster
13:34:07:250 FP indication 0x0104 / 0x0000 (0xEC1BBDFFFE871E04 / 0x1825)
13:34:07:250                       ...     (0xEC1BBDFFFE871E04 / 0x1825)
13:34:07:250 Clear fast probe timeout for cluster 0x0000, 0xEC1BBDFFFE871E04
13:34:07:255 [4] get basic cluster attr 0x0006 for 0xec1bbdfffe871e04
13:34:07:292 skip device discovery while end devices is added
13:34:07:608 ZCL got data for node=0x1825, cl=0x0000, at=0x0006, status=0x00, type=0x42
13:34:07:608 Node data 0xec1bbdfffe871e04 profileId: 0x0104, clusterId: 0x0000
13:34:07:609 Battery debug 1
13:34:07:609 Battery debug 2
13:34:07:609 Update Sensor 0xEC1BBDFFFE871E04 Basic Cluster
13:34:07:609 FP indication 0x0104 / 0x0000 (0xEC1BBDFFFE871E04 / 0x1825)
13:34:07:609                       ...     (0xEC1BBDFFFE871E04 / 0x1825)
13:34:07:609 Clear fast probe timeout for cluster 0x0000, 0xEC1BBDFFFE871E04

**Comment by Smanar** [comment]
Yeah 
>13:34:09:274 Battery debug 6 : 98

And you still have battery = null ?

**Comment by bsfaxi** [comment]
For this one, it's okay since the beginning. It had and still has the correct value. :)
The other switch is corrupt somehow I think. Don't bother with it.

**Comment by Smanar** [comment]
OK, so give up for the moment, thx ^^

**Comment by bsfaxi** [comment]
> OK, so give up for the moment, thx ^^

Thanks a lot for your precious support.

**Comment by Mimiix** [comment]
@Smanar Does this one needs to be closed when #3398 is integrated?

**Comment by Smanar** [comment]
Still missing the battery.

**Comment by cobirnm** [comment]
I have tried to use this V2_05_86 and it did not work. The issues with that version were so much that I reverted back.

**Comment by Smanar** [comment]
This code was skipped in version 86.
If you want to make a try, you need to compile the code. Do you have an unix machine ?

**Comment by cobirnm** [comment]
> This code was skipped in version 86.
> If you want to make a try, you need to compile the code. Do you have an unix machine ?

Will it be part of 87? i s will be released today, according to the shcedule.

**Comment by bsfaxi** [comment]
Hi @Smanar,
Why is it skipped? We really need it as soon as possible please.

Concerning the battery problem, I opened the concerned device. There is a defective electronic piece near the battery that needs soldering or maybe should be replaced. That could explain why we have such problem to follow the battery level. All the rest is working fine for us.

So please commit the code. You'll make at least 2 happy guys. ;)

The device:
![image](https://user-images.githubusercontent.com/23717629/98463195-dc159380-21b9-11eb-9129-3cc61ecb234e.png)

**Comment by Smanar** [comment]
> Will it be part of 87? i s will be released today, according to the shcedule.

IDK, the tuya code is "sensible" so it can be skipped form stable, not enougth time to test it. If it s not for the stable, will be for the beta, the next week.

There was a problem in PR validation, The whole commit was validated but only a part of the commit was included in the code.

**Comment by bsfaxi** [comment]
Thanks @Smanar.
We will be patient. :)

**Comment by Smanar** [comment]
Just by curiosity, I m making a change to have only 1 "sensor" device instead of 1 by endpoint.
There is someone here that can make a try ?

**Comment by bsfaxi** [comment]
Hi @Smanar,
I'll try to do a test.
Do you mean a wireless switch with 2 buttons?

**Comment by Smanar** [comment]
It s ok ^^.
I have found someone that helped me on another issue, the PR was just validated.

Hoping for no more problems.

**Comment by bsfaxi** [comment]
> Hoping for no more problems.

Well done. :)

**Comment by cobirnm** [comment]
I'm on 2.06.00 and the remote tuya switch works. On home assistant I get every time I press the switch 2 events instead of one. Has this happen to anyone?

**Comment by Smanar** [comment]
for all events ? (double long and short ?)

**Comment by cobirnm** [comment]
> for all events ? (double long and short ?)

I was only able to get short and double (1002 and 1004) but yes all duplicates

**Comment by bsfaxi** [comment]
Hi guys,
I'll give it a try today on my side and keep you posted.

**Comment by Smanar** [comment]
If I m right you have the debug on phoscon now ? in the "help" part (Haven't tried yet)
Can you show the debug when you press the button ?

**Comment by bsfaxi** [comment]
So, I upgraded :
- deconz to v2.05.88
- deconz-rest-plugin to v2.06.00
- Raspbee II firmware to v26660700

In the debug window on deconz, I activated the level INFO. I noticed only one event each time for short, double and long press:
18:33:37:565 [INFO] - Button 1002 B1 short TS0041
18:33:45:597 [INFO] - Button 1004 B1 double TS0041
18:33:53:868 [INFO] - Button 1003 B1 long TS0041

In Home Assistant, I also listened to events with type "deconz_event". And, I only have one event each time. See below:
Event 3 fired 7:10 PM:
{
    "event_type": "deconz_event",
    "data": {
        "id": "switch",
        "unique_id": "ec:1b:bd:ff:fe:76:d7:64",
        "event": 1003
    },
    "origin": "LOCAL",
    "time_fired": "2020-11-17T18:10:29.044238+00:00",
    "context": {
        "id": "057908c7d9117474811cc7b41450f412",
        "parent_id": null,
        "user_id": null
    }
}
Event 1 fired 7:07 PM:
{
    "event_type": "deconz_event",
    "data": {
        "id": "switch",
        "unique_id": "ec:1b:bd:ff:fe:76:d7:64",
        "event": 1004
    },
    "origin": "LOCAL",
    "time_fired": "2020-11-17T18:07:52.094161+00:00",
    "context": {
        "id": "dd9b8f28971e9ca823873a833d69bbda",
        "parent_id": null,
        "user_id": null
    }
}
Event 0 fired 7:07 PM:
{
    "event_type": "deconz_event",
    "data": {
        "id": "switch",
        "unique_id": "ec:1b:bd:ff:fe:76:d7:64",
        "event": 1002
    },
    "origin": "LOCAL",
    "time_fired": "2020-11-17T18:07:34.690206+00:00",
    "context": {
        "id": "a8714ba850ad6230d315cfb1809cf37c",
        "parent_id": null,
        "user_id": null
    }
}

**Comment by Smanar** [comment]
Thx ^^.

Can you do same @cobirnm the problem can come from a script too.

**Comment by cobirnm** [comment]
I'm looking at new debug feature of Deconz (verry usefull)

This is what I get:

```
19:54:08:349 [INFO] - Button 1002 B1 short TS0041
19:54:09:374 [INFO] - Button 1002 B1 short TS0041 
```

**Comment by Smanar** [comment]
So you have it 1s after, and was not from third app ...
It s the only one you have ?

**Comment by cobirnm** [comment]
> So you have it 1s after, and was not from third app ...
> It s the only one you have ?

Tuya yes. I have some from aqara and work properly.

**Comment by Smanar** [comment]
Yep it can be normal, phoson use whitelist to display devices.

BTW I haven't used the phoscon log yet, but you can't see more information when you press a button ?

**Comment by cobirnm** [comment]
> Yep it can be normal, phoscon use whitelist to display devices.
> 
> BTW I haven't used the phoscon log yet, but you can't see more information when you press a button ?

Only this:

```
23:46:03:174 [INFO] - Button 1002 B1 short TS0041
23:46:03:228 Websocket 192.168.1.91:40052 send message: {"e":"changed","id":"91","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2020-11-17T23:46:03.175"},"t":"event","uniqueid":"84:2e:14:ff:fe:e3:7e:bd-01-0006"} (ret = 2130398792)
23:46:03:241 discard sensor state push for 91: state/lastupdated (already pushed)
```

There are lots of log lines in the midle but they don't look related to the switch

**Comment by bsfaxi** [comment]
> I have also noticed that no switch is created under phoscon

Hi,
I can see the Wireless switch in Phoscon app under the Switches section.
![image](https://user-images.githubusercontent.com/23717629/99511486-99597580-2988-11eb-97c7-3daac6e03c1f.png)

Maybe you have to make a backup of your deconz installation and re-install it from scratch !

**Comment by Smanar** [comment]
Ok there is so much differences betwwen you ...
You are both on 2.06.00 and using HA with an external deconz installation ?

>There are lots of log lines in the midle but they don't look related to the switch. Is it possible to have a broken switch?

Broken switch, possible, but that make double command as bug, I don't think.
BTW I m interested by the lines in the middle, to check if there is a difference on the first command and the second, you can use some site like pastebin if the file is hudge.

**Comment by bsfaxi** [comment]
> 
> You are both on 2.06.00 and using HA with an external deconz installation ?
> 

On my side, Deconz and HA are installed separately but on the same Raspberry.

**Comment by Smanar** [comment]
Just by curiosity, you are using container ? so you have 2 on a raspberry ?

**Comment by bsfaxi** [comment]
> Just by curiosity, you are using container ? so you have 2 on a raspberry ?

No containers. Only 2 plain and supported installations.

**Comment by cobirnm** [comment]
> Just by curiosity, you are using container ? so you have 2 on a raspberry ?

My config is docker instalation in a RPI3. I run deconz container on and homeassistant containers on different RPI's.

Regarding the switch I have made a fresh install of Deconz and added only the tuya switch. The first thing I noticed was when adding it it showed in Deconz for 2 or 3 seconds as "On/Off light 2" and then changed the name to "Switch 2".

When I look at phoscon I can see it added as "On/Off light 2" as you can see in the picture:

![image](https://user-images.githubusercontent.com/45829329/99601030-7b2a5e80-29f6-11eb-929d-80ba920bc34e.png)

On Deconz it's as "Switch 2":

![image](https://user-images.githubusercontent.com/45829329/99601098-a614b280-29f6-11eb-94bf-410d6547ef7d.png)

I have used the debug view since the begining and have recorded the logs (attaching the file). I don't know if it will help or not!
[Tuya Full log.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5563362/Tuya.Full.log.txt)

**Comment by Smanar** [comment]
I think the log can be usefull yes, I m asking to other dev ATM, because it s realy strange, the bug is realy on zigbee side.

**Comment by Smanar** [comment]
Ok so I m sorry, but the only way to be sure it s sniffing directly the zigbee traffic.
But I don't think the problem is from the deconz core, with all users that are using it, not possible you can be the only with that.

Except re including the device, to remake the bind/reporting, there is realy nothing you can do on your side.

**Comment by cobirnm** [comment]
> Ok so I m sorry, but the only way to be sure it s sniffing directly the zigbee traffic.
> But I don't think the problem is from the deconz core, with all users that are using it, not possible you can be the only with that.
> 
> Except re including the device, to remake the bind/reporting, there is realy nothing you can do on your side.
> 
> You have this bug from the start ?
> 
> No other device to make tests ?

I only have this device that I bought from zemismart. I have been able to get a Tuya zigbee hub and have tryed the switch. It works as it shoulld.

I can get in Tuya app single press, double press and long press.
In Deconz I can only get single press and double press!

The other wireless switch that I have are from Aqara, and there is no problem there!

I'n convinced that the issue might be on what I have reported earlier in a previous post first it is added as a light and only then it changes to a swhitch 

"(Regarding the switch I have made a fresh install of Deconz and added only the tuya switch. The first thing I noticed was when adding it it showed in Deconz for 2 or 3 seconds as "On/Off light 2" and then changed the name to "Switch 2".)"

**Comment by bsfaxi** [comment]
Maybe you need to clean up the Deconz database manually. It's a file called "zll.db" and accessible with a sqlite client.
I had to do that for some deleted devices that reappears each time I had to restart DeConz.
Then re-add your device.

**Comment by cobirnm** [comment]
> Maybe you need to clean up the Deconz database manually. It's a file called "zll.db" and accessible with a sqlite client.
> I had to do that for some deleted devices that reappears each time I had to restart DeConz.
> Then re-add your device.

The behaviour I described was from a clean install and clean database. I made a reset in Phoscon, then deleted docker container, deleted all the db files (zll.db, zcldb.txt, session.default and config.conf) and then started from scratch. For sure it's not DB related!

**Comment by cobirnm** [comment]
I've searching the logs and the behavior I described can be seen:

```
23:11:30:410 HTTP client GET /usr/share/deCONZ/webapp//language/en/lights-en.json
23:11:30:411 	/language/en/lights-en.json --> HTTP/1.1 404 Not Found
23:11:30:412 http client (192.168.1.202) handled 2 requests
23:11:30:414 Idle timer triggered
23:11:30:415 create binding for attribute reporting of cluster 0x0006
23:11:30:415 queue binding task for 0x842E14FFFEE37EBD, cluster 0x0006
23:11:30:416 Force binding of attribute reporting for node On/Off light 2
23:11:30:417 Force read attributes for ZHASwitch SensorNode Switch 2
```

First I get "23:11:30:416 Force binding of attribute reporting for node On/Off light 2" and then in a fraction of a second I get "23:11:30:417 Force read attributes for ZHASwitch SensorNode Switch 2"

For I can'f find anything else but I bet that this is causing some duplicate entity in the code that then generates the duplicate entries.... (This is as far as I can get with my knowledge)

**Comment by Smanar** [comment]
It s a long story but the device can have entries in "sensors" and "lights" (the tuya inclusion is special ATM), but zigbee commands are send at device, so even if the code choose one of the othern the command will be send at same device.

You see something special in log when using the long press ?

You can try to play with the "binding" or "reporting" but this is reset when you re-include the device, so after so much tries, I think the test was done.

**Comment by cobirnm** [comment]
I've made several attempts and none of them was successful.
I have ended up going around this situation by inserting a 2 seconds delay at the end of a home assistant automation. This way I can get a working switch.

**Comment by deennoo** [comment]
Hi there,

Raspbee fw : 26390500
Phoscon App : 2.07.01 / 08/12/2020

On RPI

Tuya TS0041 is still reconize as a bulb

![Capture](https://user-images.githubusercontent.com/9532206/104087513-86fd0900-5260-11eb-9616-72914e97fec1.PNG)

**Comment by bsfaxi** [comment]
> Hi there,
> 
> Raspbee fw : 26390500
> Phoscon App : 2.07.01 / 08/12/2020
> 
> On RPI
> 
> Tuya TS0041 is still reconize as a bulb

I had the same issue recently. Delete the device and re-pair again from the Phoscon Sensors screen.
If successful, it will appear in the deCONZ app and not in the Phoscon. That's Normal. :) 
![image](https://user-images.githubusercontent.com/23717629/104087679-ced06000-5261-11eb-9d18-7414fa8a9425.png)

**Comment by Smanar** [comment]
@deennoo what is your device ^^, the model id mean nothing for tuya, I have searched your manufacture name PESZE... and I don't find it on the code.

Wired switches are reconized as light.

**Comment by bsfaxi** [comment]
Hi @Smanar,
The TS0041 model is the wireless switch (not the wired one) with 1 button, TS0042 with 2 buttons and TS0043 with 3 buttons.
They are the Tuya scene switches. I think they even released a 4 buttons wireless switch recently.
My 2 cents. 😃

**Comment by Smanar** [comment]
So if you have the 1 button model, this one is not yet in the code.
The supported one are 
```
                    else if ((sensorNode->manufacturer() == QLatin1String("_TZ3000_bi6lpsew")) ||
                        (sensorNode->manufacturer() == QLatin1String("_TZ3400_keyjhapk")) ||
                        (sensorNode->manufacturer() == QLatin1String("_TYZB02_key8kk7r")) ||
                        (sensorNode->manufacturer() == QLatin1String("_TZ3400_keyjqthh")) ||
                        (sensorNode->manufacturer() == QLatin1String("_TZ3400_key8kk7r")) ||
                        (sensorNode->manufacturer() == QLatin1String("_TZ3000_vp6clf9d")) ||
                        (sensorNode->manufacturer() == QLatin1String("_TYZB02_keyjqthh")))
```
But easy to add them, Do you know how to compile the code to test it @deennoo ?

**Comment by bsfaxi** [comment]
> I've made several attempts and none of them was successful.
> I have ended up going around this situation by inserting a 2 seconds delay at the end of a home assistant automation. This way I can get a working switch.

I now have the same issue with all my TUYA wireless switches with models TS0041, TS0042 and TS0043!
I receive the button event twice, with 1 second interval.
This happens with 2 different systems: one RPI4 with HA addon (Docker) and a Raspbee II, and one RPI 4 with plain Raspbian and deCONZ installation and a ConBee II.

**Comment by Smanar** [comment]
Suddently, without a change ?

All your device have the "power configuration" cluster 0x0001 ?

**Comment by deennoo** [comment]
> @deennoo what is your device ^^, the model id mean nothing for tuya, I have searched your manufacture name PESZE... and I don't find it on the code.
> 
> Wired switches are reconized as light.

mine is a wireless switch with 1 button

I manage to get it work on a zigate with beta fw

device name is : _TZ3000_peszejy7, also annoncing as a ts0043

**Comment by bsfaxi** [comment]
> Suddently, without a change ?
> 
> All your device have the "power configuration" cluster 0x0001 ?

@Smanar 
The fact is it was working correctly when you provided the support of the new devices. Waiting for the official support on a stable deCONZ version to setup those wireless switches on my production environment, I paired them with a Tuya GW temporarily. I finally ended up by switching them on my prod environment yesterday.
Since, deCONZ had several version ahead. I don't remember which one. I can give it a try on my DEV environment if you want to test with older versions.

What's weird is that the TS0043 model is working fine !


> I manage to get it work on a zigate with beta fw + Domoticz plugin on beta version who already have ts0043 from LoraTap on test

@deennoo,
Is it possible for you to test the TS0043 to confirm its behavior please?
Thanks.

**Comment by Smanar** [comment]
@deennoo just added your switch https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4157
Just to be sure can you confirm me the manufacture number and a MAC address ?

@bsfaxi idk, I realy haven't see modification on code that can provoke that.
And I have this problem in all version, but not all users, I realy don't have idea where it can be from.

This modifications will solve some problem with tuya device https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4087 but it seem it not solve this problem.

I will finsih to make a hack direclty in the code ....

**Comment by bsfaxi** [comment]
> Some one have tried to remove the bind using the GUI ? I don't think it can be a pool issue for long or double press.

How to do that ?

**Comment by Smanar** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2373#issuecomment-595414912

With the cluster 0x0006 but the "unbind" button. Perhaps need to awake the device

**Comment by bsfaxi** [comment]
I did the "unbind" successfully (see picture in the bottom).
But, it's still behaving the same.

Log:
17:17:09:025 GW firmware version: 0x26690700
**17:17:11:987 [INFO] - Button 1002 B1 short TS0041**
17:17:12:222 	0xEC1BBDFFFE5B81AD force poll (2)
17:17:12:242 ZCL attribute report 0xEC1BBDFFFE5B81AD for cluster: 0x0006, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
17:17:12:957 ZCL attribute report 0xBC33ACFFFE170545 for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
**17:17:13:013 [INFO] - Button 1002 B1 short TS0041**

![image](https://user-images.githubusercontent.com/23717629/104208464-e6117800-5430-11eb-8ddc-f3f364c95fd8.png)
