### ISSUE TITLE
with latest beta - 2.19.0 - huge delay on group calls and sometimes not even executed

### ISSUE THREAD

**Issue by holli73** [dresden-elektronik/deconz-rest-plugin#6445]
## Describe the bug

i have 3 instance running and updated all to the latest beta (conbee/rasbpee) and now if i make group calls (i must use group as i do have rooms with up to 20 lights) f.ex. call group bad with scene1 takes up to 10 seconds that the lights go on sometimes they do not turn on at all..

## Steps to reproduce the behavior

  just make scene calls to group's with lot of devices (lights)

## Expected behavior

no delay on these calls

## Environment

Linux pi4-deconz-bad-og 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux
ConBee
2.19.00 / 19.9.2022
26400500

Linux obelix 4.15.0-192-generic #203-Ubuntu SMP Wed Aug 10 17:40:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
conbee on x64 linux - 2.19.00 / 19.9.2022
26400500

Linux rasp-eg-verteilerkasten 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux
RaspBee
2.19.00 / 19.9.2022
26400500

**Comment by Mimiix** [comment]
Can you please provide the enviroment info as mentioned in the template. 

Additionally can you provide some logs ?

**Comment by holli73** [comment]
@Mimiix - sure i can provide logs - just let me know what kind of debug you need

i did update the initial post - hope the env. is ok now - these are dedicated devices for deconz only - only obelix is a big host with 3.6ghz xeon and 16 cores with some other software but this should be fine - as i do have deconz since years - i believe one of the first user with having a real big env. up to 100 lights and the cause for developing conbee and support x64 linux...

i did downgrade all 3 instances to 2.18.02 and the delay is gone

**Comment by Smanar** [comment]
I m on it too.
My tuya device router have 10 s delay, a rollback solve the issue.
I m not using group.

**Comment by popy2k14** [comment]
I have a very simliar issue on my network, but for quite some stable versions (i think at least 3 stable versions).
Now i am on 1.18.2 stabe and my network get's unstable (slow reacting time, lost commands, ...) after some time.

PS.: I am NOT using HA groups, i am using deconz groups. So no issue with too much commands at the same time!

What i have tried:
 * restart of deconz addon in HA -> solves the issue 100%
 * A HA core restart -> does not solve the issue
 
 Here is the thread on the forums:  https://forum.phoscon.de/t/zigbee-network-becomes-unresponsive-after-a-1-2-weeks/2563
 Also with an log at the time it was slow with Error, Error L2, Info, Info L2 activated.
 In there is nothing problematic.

**Comment by popy2k14** [comment]
Today it happend again. i woke up @ ~07:30 and all was slow as hell 5-10 seconds delay.
Now i had time to make a log.
I have done the following:
- activated APS, APS L2 , Error, Error L2, Info, Info L2 in debug view in VNC
- pressed my hue dimmer switch on (which switches on a scene), off which switches off a group two times at around ~12:30
- extracted the log and cutted it from 20:00 yesterday up until now
- deactivated APS, APS L2 , Error, Error L2, Info, Info L2 in debug view in VNC

Here it is: [deconz.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/9844117/deconz.zip)

PS.: i dont know if it is the same issue as the OP's issue. if not, sorry for hijacking this thread and please advice if i should open a new issue.

thx

**Comment by Smanar** [comment]
Ok perhaps nothing to see with the issue but some test on my side with a tuya device impacted by same issue

**On version 2.18**

The issue don't happen all the time, and the device is working even with the request spam

```
1:57:31:431 Send Tuya request 0x84FD27FFFE892E2C : Dp_type: 0x01, Dp_identifier 0x01, data: 01
21:57:31:432 add task 57419 type 41 to 0x84FD27FFFE892E2C cluster 0xEF00 req.id 74
21:57:31:433 delay sending request 74 dt 0 ms to 0x84FD27FFFE892E2C, ep: 0x01 cluster: 0xEF00 onAir: 1
21:57:31:434 delay sending request 74 ep: 0x01 cluster 0xEF00 to 0x84fd27fffe892e2c onAir 1
21:57:31:512 delay sending request 74 dt 0 ms to 0x84FD27FFFE892E2C, ep: 0x01 cluster: 0xEF00 onAir: 1
21:57:31:514 delay sending request 74 ep: 0x01 cluster 0xEF00 to 0x84fd27fffe892e2c onAir 1
21:57:31:564 Erase task req-id: 73, type: 41 zcl seqno: 23 send time 0, profileId: 0x0104, clusterId: 0xEF00
21:57:31:565 APS-DATA.request id: 74, addrmode: 0x03, addr: 0x84fd27fffe892e2c, profile: 0x0104, cluster: 0xEF00, ep: 0x01 -> 0x01 queue: 1 len: 10 tx.options 0x04
21:57:31:568     asdu (length: 10): 11180000180101000101
21:57:31:570 Delay APS request id: 74 to 0x40FF, profile: 0x0104 cluster: 0xEF00 node already has busy 1
21:57:31:572 APS-DATA.confirm id: 73, status: 0x00 SUCCESS
21:57:31:574 APS-DATA.confirm request id: 73 -> erase from queue
21:57:31:609 aps request id: 73 finished, erase from queue
21:57:31:659 APS-DATA.indication srcAddr: 0x40ff, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0xEF00, lqi: 167, rssi: -70
21:57:31:662     asdu: 092c02063a02020004000001d4
21:57:31:670 Tuya debug Request : Address 0x84FD27FFFE892E2C, Endpoint 0x01, Command 0x02, Payload 063a02020004000001d4
21:57:31:673 Tuya debug 4 : Address 0x84FD27FFFE892E2C Payload 063a02020004000001d4
21:57:31:675 Tuya debug 5 : Status: 6 Transid: 58 Dp: 514 (0x02,0x02) Fn: 0 Data 468
21:57:31:677 APS-DATA.request id: 77, addrmode: 0x02, addr: 0x40ff, profile: 0x0104, cluster: 0xEF00, ep: 0x01 -> 0x01 queue: 1 len: 5 tx.options 0x04
21:57:31:681     asdu (length: 5): 102c0b0200
21:57:31:683 Delay APS request id: 77 to 0x40FF, profile: 0x0104 cluster: 0xEF00 node already has busy 1
```

Deconz is creating a new request and totaly spam the device with it. The good one have the number 74, but it create too the number 77, and ect ....

It create a new one after new tuya report
```

21:57:33:664 Tuya debug 4 : Address 0x84FD27FFFE892E2C Payload 063b0101000101
21:57:33:665 Tuya debug 5 : Status: 6 Transid: 59 Dp: 257 (0x01,0x01) Fn: 0 Data 1
21:57:33:667 APS-DATA.request id: 105, addrmode: 0x02, addr: 0x40ff, profile: 0x0104, cluster: 0xEF00, ep: 0x01 -> 0x01 queue: 7 len: 5 tx.options 0x04
```

**On version 2.19**

**Comment by popy2k14** [comment]
so it seems we are suffering from the same issue!
After i activated APS debugs ~12:30 in my log you also see mutliple:

```
12:31:18:044 Delay APS request id: 191 to 0xD245, profile: 0x0104 cluster: 0x0406 node already has busy 1
12:31:18:052 Delay APS request id: 191 to 0xD245, profile: 0x0104 cluster: 0x0406 node already has busy 1
....
12:31:18:552 Delay APS request id: 191 to 0xD245, profile: 0x0104 cluster: 0x0406 node already has busy 1
...
12:31:18:558 Delay APS request id: 191 to 0xD245, profile: 0x0104 cluster: 0x0406 node already has busy 1
...
12:31:18:608 Delay APS request id: 191 to 0xD245, profile: 0x0104 cluster: 0x0406 node already has busy 1
12:31:18:622 Delay APS request id: 191 to 0xD245, profile: 0x0104 cluster: 0x0406 node already has busy 1
```

in the same second spamming the network.
(Please correct me if i am wrong).

**Comment by Smanar** [comment]
For me yes, on the version 2.18 deconz create a new request (74, 77, ect ...) , on the version 2.19, it is using the same (135 for me 191 for you), but have almost the same reaction

**Comment by popy2k14** [comment]
ok, thx for confirming. This problem has been bugging me for a few versions now. Nice that i am not alone and we can debug it togethher. Maybe there need to be more debug messages compiled in to find the root cause. Sadly i am not able to do that.
Are you able to compile it?

If i can help debug any further just let me know. as stated: in my network the issue comes upo after a few days.

PS.: so that we see nothing in the logs (alongside from spaming) in error condition, can i restart my addon/deconz to get normal function of my network back? Or is anything i can help?

**Comment by Smanar** [comment]
On my side rolling back help a little, the device is working better, but there is still somes issue on logs
Here I have a more complete logs cleaned, but I don't see anything yet

```
13:06:48:911 Send Tuya request 0x84FD27FFFE892E2C : Dp_type: 0x01, Dp_identifier 0x01, data: 00
13:06:48:912 add task 4425 type 41 to 0x84FD27FFFE892E2C cluster 0xEF00 req.id 225
13:06:48:913 APS-DATA.request id: 225, addrmode: 0x03, addr: 0x84fd27fffe892e2c, profile: 0x0104, cluster: 0xEF00, ep: 0x01 -> 0x01 queue: 2 len: 10 tx.options 0x04
13:06:48:915 	asdu (length: 10): 11550000550101000100
13:06:51:643 aps request id: 249 prf: 0x0000 cl: 0x0031 timeout (confirmed: 0) to 0x84FD27FFFE892E2C (0x40FF)
13:06:51:644 aps request id: 249 prf: 0x0000 cl: 0x0031 timeout NOT confirmed to 0x84FD27FFFE892E2C (0x40FF)
13:06:51:725 aps request id: 249 failed, erase from queue
13:06:51:727 emit artificial APSDE-DATA.confirm id: 249
13:06:51:803 aps request id: 249 failed, erase from queue
13:06:53:645 APS-DATA.indication srcAddr: 0x40ff, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0000, lqi: 167, rssi: -70
13:06:53:646 	asdu: 085e0a01002042e2ff201fe4ff2000
13:06:53:648 Node data 0x84fd27fffe892e2c profileId: 0x0104, clusterId: 0x0000
13:06:53:650 ZCL attribute report 0x84FD27FFFE892E2C for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:06:53:652 	payload: 01002042e2ff201fe4ff2000
13:06:53:654 Websocket 127.0.0.1:60610 send message: {"attr":{"id":"3","lastannounced":null,"lastseen":"2022-10-22T11:06Z","manufacturername":"_TZE200_la2c2uo9","modelid":"TS0601","name":"Dimmer salon","productid":"Tuya_DIMSWITCH MS-105Z","swversion":null,"type":"Dimmable light","uniqueid":"84:fd:27:ff:fe:89:2e:2c-01"},"e":"changed","id":"3","r":"lights","t":"event","uniqueid":"84:fd:27:ff:fe:89:2e:2c-01"} (ret = 356)
13:06:53:657 APS-DATA.request id: 247, addrmode: 0x02, addr: 0x40ff, profile: 0x0104, cluster: 0x0000, ep: 0x01 -> 0x01 queue: 3 len: 5 tx.options 0x04
13:06:53:660 	asdu (length: 5): 105e0b0a00
13:06:54:060 APS-DATA.indication srcAddr: 0x40ff, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0000, lqi: 167, rssi: -70
13:06:54:062 	asdu: 085e0a01002042e2ff201fe4ff2000
13:06:54:064 Node data 0x84fd27fffe892e2c profileId: 0x0104, clusterId: 0x0000
13:06:54:065 ZCL attribute report 0x84FD27FFFE892E2C for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:06:54:066 	payload: 01002042e2ff201fe4ff2000
13:06:54:068 APS-DATA.request id: 252, addrmode: 0x02, addr: 0x40ff, profile: 0x0104, cluster: 0x0000, ep: 0x01 -> 0x01 queue: 3 len: 5 tx.options 0x04
13:06:54:069 	asdu (length: 5): 105e0b0a00
13:06:54:198 APS-DATA.indication srcAddr: 0x40ff, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0000, lqi: 167, rssi: -70
13:06:54:200 	asdu: 085e0a01002042e2ff201fe4ff2000
13:06:54:202 Node data 0x84fd27fffe892e2c profileId: 0x0104, clusterId: 0x0000
13:06:54:203 ZCL attribute report 0x84FD27FFFE892E2C for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:06:54:204 	payload: 01002042e2ff201fe4ff2000
13:06:54:205 APS-DATA.request id: 255, addrmode: 0x02, addr: 0x40ff, profile: 0x0104, cluster: 0x0000, ep: 0x01 -> 0x01 queue: 4 len: 5 tx.options 0x04
13:06:54:206 	asdu (length: 5): 105e0b0a00
13:06:54:207 Delay APS request id: 255 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:222 Delay APS request id: 255 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:291 Delay APS request id: 255 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:303 APS-DATA.indication srcAddr: 0x40ff, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0000, lqi: 167, rssi: -70
13:06:54:305 	asdu: 085e0a01002042e2ff201fe4ff2000
13:06:54:307 Delay APS request id: 255 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:308 Node data 0x84fd27fffe892e2c profileId: 0x0104, clusterId: 0x0000
13:06:54:309 ZCL attribute report 0x84FD27FFFE892E2C for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:06:54:310 	payload: 01002042e2ff201fe4ff2000
13:06:54:311 APS-DATA.request id: 2, addrmode: 0x02, addr: 0x40ff, profile: 0x0104, cluster: 0x0000, ep: 0x01 -> 0x01 queue: 5 len: 5 tx.options 0x04
13:06:54:311 	asdu (length: 5): 105e0b0a00
13:06:54:312 Delay APS request id: 255 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:313 Delay APS request id: 2 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:390 Delay APS request id: 255 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:392 Delay APS request id: 2 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:394 poll node 84:fd:27:ff:fe:89:2e:2c-01
13:06:54:395 Poll light node Dimmer salon
13:06:54:396 Erase task req-id: 225, type: 41 zcl seqno: 85 send time 5, profileId: 0x0104, clusterId: 0xEF00
13:06:54:399 APS-DATA.confirm id: 225, status: 0x00 SUCCESS
13:06:54:403 APS-DATA.confirm request id: 225 -> erase from queue
13:06:54:461 Delay APS request id: 2 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:463 aps request id: 225 finished, erase from queue
13:06:54:481 APS-DATA.indication srcAddr: 0x40ff, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0000, lqi: 167, rssi: -70
13:06:54:484 	asdu: 085e0a01002042e2ff201fe4ff2000
13:06:54:487 Delay APS request id: 2 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:488 Node data 0x84fd27fffe892e2c profileId: 0x0104, clusterId: 0x0000
13:06:54:489 ZCL attribute report 0x84FD27FFFE892E2C for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:06:54:490 	payload: 01002042e2ff201fe4ff2000
13:06:54:491 APS-DATA.request id: 5, addrmode: 0x02, addr: 0x40ff, profile: 0x0104, cluster: 0x0000, ep: 0x01 -> 0x01 queue: 5 len: 5 tx.options 0x04
13:06:54:492 	asdu (length: 5): 105e0b0a00
13:06:54:493 Delay APS request id: 2 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:494 Delay APS request id: 5 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:512 APS-DATA.confirm id: 239, status: 0x00 SUCCESS
13:06:54:516 APS-DATA.confirm request id: 239 -> confirmed, timeout 0
13:06:54:518 Delay APS request id: 2 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:521 Delay APS request id: 5 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:583 Delay APS request id: 2 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:586 Delay APS request id: 5 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:588 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 167, rssi: -70
13:06:54:592 	asdu: 7c000300019d9e02ffff2e21002c2e89feff27fd84ff403501009f
13:06:54:594 APS-DATA.indication request id: 239 -> finished
13:06:54:597 APS-DATA.request id: 239 erase from queue
13:06:54:597 APS-DATA.request id: 7, addrmode: 0x03, addr: 0x00212effff029e9d, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 5 len: 2 tx.options 0x00
13:06:54:598 	asdu (length: 2): 7d01
13:06:54:599 Delay APS request id: 2 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:600 Delay APS request id: 5 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:699 APS-DATA.indication srcAddr: 0x40ff, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0000, lqi: 167, rssi: -70
13:06:54:701 	asdu: 085e0a01002042e2ff201fe4ff2000
13:06:54:703 Delay APS request id: 2 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:704 Delay APS request id: 5 to 0x40FF, profile: 0x0104 cluster: 0x0000 node already has busy 3
13:06:54:705 Node data 0x84fd27fffe892e2c profileId: 0x0104, clusterId: 0x0000
13:06:54:706 ZCL attribute report 0x84FD27FFFE892E2C for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:06:54:707 	payload: 01002042e2ff201fe4ff2000
13:06:54:708 APS-DATA.request id: 9, addrmode: 0x02, addr: 0x40ff, profile: 0x0104, cluster: 0x0000, ep: 0x01 -> 0x01 queue: 6 len: 5 tx.options 0x04
13:06:54:708 	asdu (length: 5): 105e0b0a00
```

**Comment by Smanar** [comment]
@popy2k14 
Your error are for a presence sensor, so pehraps more classic, as thoses device are lazy.

**Comment by Mimiix** [comment]
> Today it happend again. i woke up @ ~07:30 and all was slow as hell 5-10 seconds delay. Now i had time to make a log. I have done the following:
> 
> * activated APS, APS L2 , Error, Error L2, Info, Info L2 in debug view in VNC
> * pressed my hue dimmer switch on (which switches on a scene), off which switches off a group two times at around ~12:30
> * extracted the log and cutted it from 20:00 yesterday up until now (otherwise it where >70MB)
> * deactivated APS, APS L2 , Error, Error L2, Info, Info L2 in debug view in VNC
> 
> Here it is: [deconz.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/9844117/deconz.zip)
> 
> PS.: i dont know if it is the same issue as the OP's issue. if not, sorry for hijacking this thread and please advice if i should open a new issue.
> 
> PS PS.: i have not restarted the addon yet and can test something
> 
> thx

Hi!

Can you share in pastebin or txt format ? Thanks :)

**Comment by popy2k14** [comment]
no, because also when i just want to post the log from 12:30 it exceeds the 5112kb limit.
You can doenload it here, it's an github link :-)

**Comment by Smanar** [comment]
But you have take this long during a slowdown ?

Do you know what is the 0x8F11 device (0x680AE2FFFE36D57F) ? ikea rollerblind ?

**Comment by popy2k14** [comment]
> @popy2k14 Your error are for a presence sensor, so pehraps more classic, as thoses device are lazy.
> 
> But you have take this long during a slowdown ?
> 
> Do you know what is the 0x8F11 device (0x680AE2FFFE36D57F) ? ikea rollerblind ?

Yes, mostly it takes a few days. The last time it took 9 days, but also had 2 weeks.

Yes, 680AE2FFFE36D57F is an fyrtur:
`
"77":{"config":{"on":true,"reachable":true},"ep":1,"etag":"1cb4c33f7245982d2e51be26583aedbf","lastannounced":"2022-09-24T08:03:07Z","lastseen":"2022-10-22T12:16Z","manufacturername":"IKEA of Sweden","modelid":"FYRTUR block-out roller blind","name":"Rollo Julian","state":{"battery":100,"lastupdated":"2022-10-22T12:00:46.717"},"swversion":"2.3.088","type":"ZHABattery","uniqueid":"68:0a:e2:ff:fe:36:d5:7f-01-0001"}`

**Comment by popy2k14** [comment]
> > Today it happend again. i woke up @ ~07:30 and all was slow as hell 5-10 seconds delay. Now i had time to make a log. I have done the following:
> > 
> > * activated APS, APS L2 , Error, Error L2, Info, Info L2 in debug view in VNC
> > * pressed my hue dimmer switch on (which switches on a scene), off which switches off a group two times at around ~12:30
> > * extracted the log and cutted it from 20:00 yesterday up until now (otherwise it where >70MB)
> > * deactivated APS, APS L2 , Error, Error L2, Info, Info L2 in debug view in VNC
> > 
> > Here it is: [deconz.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/9844117/deconz.zip)
> > PS.: i dont know if it is the same issue as the OP's issue. if not, sorry for hijacking this thread and please advice if i should open a new issue.
> > PS PS.: i have not restarted the addon yet and can test something
> > thx
> 
> Hi!
> 
> Can you share in pastebin or txt format ? Thanks :)

It's an txt file inside the zip. Pastebin 512kb limit will be exceeded with this.

**Comment by Smanar** [comment]
Ok so manup is making some tries ATM.
By curiosity you have all a conbee 1 ?

**Comment by popy2k14** [comment]
thx to step in @manup 
Mine is an conbee 2 with firmware 0x26780700 running about ~25 days.
But i also had this issue before the firmware 0x26780700.

Which firmware did you flashed and which hardware do you have?

**Comment by popy2k14** [comment]
PS.: besideds the "has busy" similarities our logs have. Mine has over ~5000x/day entries of "No presence sensor found for 0x001788010328B729, endpoint: 0x02" on various hue motion sensors (on log level "info").
Dont know if this has todo with this issue or is an side effect.
Just want to let you guys know.

Please advice if i should open another issue.

**Comment by popy2k14** [comment]
Another log entry which is over ~14000x/day in my log is:

`12:33:32:171 Skip idle timer callback, too early: elapsed 840 msec`

Note, also on log level "info".

**Comment by Smanar** [comment]
I m ATM on 26400500 but this issue concern probably only conbee 1

>No presence sensor found for 0xXXXXXXXXXXXXXXXX, endpoint: 0xXX"

This error happen if you receive data on the presence sensor, but not entry with it in the API. Need to check the device cluster, but can be because you are using the IAS cluster instead.
Not important if the device is working.

>12:33:32:171 Skip idle timer callback, too early: elapsed 840 msec

This one happen if deconz is too fast ^^, and try to make an action too fastly
```

/*! Handle idle states.

    After IDLE_LIMIT seconds user inactivity this timer
    checks if nodes need to be refreshed. This is the case
    if a node was not refreshed for IDLE_READ_LIMIT seconds.
 */
void DeRestPlugin::idleTimerFired()
{
    // Use extra QElapsedTimer since QTimer seems sometimes to
    // fire in < 1 sec. intervals (after database write?).
    if (d->idleTimer.elapsed() < (IDLE_TIMER_INTERVAL - 50)) // -50 : don't be too strict
    {
        DBG_Printf(DBG_INFO, "Skip idle timer callback, too early: elapsed %lld msec\n", d->idleTimer.elapsed());
        return;
    }
```

**Comment by popy2k14** [comment]
not what i wanted to hear :-(
I am on conbee II with a very similar issue!
How can i help to debug this one?
My guess is that it has todo with the high cpu usage -> deconz does something in an loop which get's triggered by something.

ok, thanks for clearing things up on the log spamming.
Yes, the motion sensors working and the "No presence sensor found for 0xXXXXXXXXXXXXXXXX, endpoint: 0xXX" also here after restart of deconz.
So i would ignore them for now.

PS.: would'nt it be good to not spam the log with these on just "info" log level?

**Comment by SwoopX** [comment]
The `"No presence sensor found for 0xXXXXXXXXXXXXXXXX, endpoint: 0xXX"` is just a blemish and nothing to worry about...

**Comment by popy2k14** [comment]
@SwoopX thx for confirming the "No presence..." Message.

Any hints about the massive "Skip idle timer callback..." Messages?

Does this maybe have todo with the unstable/slow network and high CPU usage?

**Comment by manup** [comment]
Hi based on Smanars logs I digged a bit deeper, the FTDI driver didn't like how it was configured causing data written not to be flushed (stuck in the pipe) for ConBee I and RaspBee I (and also with a small extra delay on ConBee II and RaspBee II but less bad).

Can you please try the following test version (Raspbian 32-bit), it works correct in my test setups now 

[deconz_2.19.00-raspbian-buster-beta_armhf.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/9844685/deconz_2.19.00-raspbian-buster-beta_armhf.zip)

`sudo dpkg -i deconz_2.19.00-raspbian-buster-beta_armhf.deb`

**Comment by popy2k14** [comment]
@manup thx for digging into this.
Just to get you right, this also affects conbee II?

Sadly I use the managed HA add-on.
Any hints how i can test this on my odroid n2+?

Just because i am curious: since which version is the ftdi configured like this?

Could this issue cause the high CPU load i have noticed? (As an side effect)

**Comment by Smanar** [comment]
From manup on discord
`ConBee I and RaspBee I mostly yes, the II versions where affected too but with only a very small delay`

I haven't issue on version < 2.19 on my side

**Comment by manup** [comment]
Sorry now it gets a bit complicated ;)
The Add-on is on v2.18.2, this and prior versions, could have delays on a higher level depending on the setup, this is fixed in v2.19.0.

But v2.19.0  before above test version has the serial port not flushing correctly which affects mainly ConBee I and RaspBee I, for ConBee II this could add < 5ms delay for some commands which were send last so it wasn't that noticeable as on I versions.

@Smanar I'm think we're ready for the v2.19.1 stable now

**Comment by popy2k14** [comment]
@manup ok got you.
So do you think my issue another one or should be solved with this?
Like @Smanar stated, another dev also have the slow down after a week or so.

How should we progress with this issue?
Try 2.19.1 and see if it is solved?

Thx

**Comment by popy2k14** [comment]
Here are some people with the exact same issue:

https://github.com/home-assistant/addons/issues/2716

The question is: is this deconz or HA related?

@Smanar the dev from discord you have spoken above, which has the same issue as me. Does he run deconz as HA addon or not?

**Comment by manup** [comment]
v2.19.1 is freshly out and should arrive in the add-on soon.

>How should we progress with this issue?
>Try 2.19.1 and see if it is solved?

Yes that would be great, hopefully this solves the issue.

**Comment by popy2k14** [comment]
@manup ok, will try the new version and report back. Also will post this info in the mentioned HA thread above.

Thx

**Comment by Ltek** [comment]
19.1 still hosed, 100% unusable. Reverted to 18.2 and works great.
in 19x1... any command to a light on/off/color/etc takes 30 seconds to execute.

**Comment by Smanar** [comment]
@cwildfoerster you have too the issue ?
And if you try with the version in this issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6445#issuecomment-1287826368 ?

**Comment by holli73** [comment]
@manup - i have now 2.19.1 in place since 2 days and it looks ok - i did have some few misses but no delays so far.

thanks
holli

**Comment by popy2k14** [comment]
Also running 2.19.1 now on my HA instance.
Hope my high cpu load issues are also solved with this release.
Otherwise i will come back here.

**Comment by cwildfoerster** [comment]
> @cwildfoerster you have too the issue ? You all a conbee 1 ? And if you try with the version in this issue [#6445 (comment)](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6445#issuecomment-1287826368) ?

No, Raspbee II with docker deconz. But its running for me like is seems for everybody, sometimes good, sometimes delays up to a minute, with some devices not receiving the command at all.

**Comment by popy2k14** [comment]
In my case i have an conbee II.
When the network is slow and unresponsive (or drops commands) the cpu usage of the HA addon is high!
15% instead 0,5% after restart.

Can you guys please look at the cpu usage of deconz when the issues happen?

**Comment by Smanar** [comment]
I have see somes devs with the same issue with the last version (cpu load increase), so I think they are on it ATM

**Comment by popy2k14** [comment]
@Smanar 
Do you have please some reference for this?
Link or anything?

I am interested in this particular issue because it's plaguing my setup for some time now.

Thx

**Comment by Smanar** [comment]
No it's a discussionon the discord private channel.
There is a new PR to correct something if you have ZGP device, but they are still searching.

**Comment by holli73** [comment]
@manup - i had to get down again on my pi's as after some time i lost too many calls (no reaction at all for group and scene calls)

on my raspbee (pi3) and conbee (on pi4) i'm back on 2.18 
on the x64 (conbee) - i'm still on the 2.19.1 as there was no impact noticeable so far

but i still believe that even with 2.18 it is not as good as it was with earlier releases...

thanks
holli

**Comment by manup** [comment]
@holli73 thanks for the reports, we're currently investigate what could be the root of this, fingers crossed to find a fix asap as it also happens in one developer setup. It looks like some setup/device specific issue causes this, I can't see the problem in my personal networks.

Do you have any ZGP switches in use? Yesterday we found one problem there this can lead to broadcasts/group casts flooding the network, fixed in https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6482

However I think there are more places with similar scheduling problems, which try to identify with logs and performance data from `perf record`.

**Comment by holli73** [comment]
@manup maybe you remember i only have oscam gu10 and oscam surface tw devices - i do have some oscam e27 as well but only 3 or 4 - i do not have any other devices - within one room i do have one e27 from philips and only one of this philips switches (4 button) 

best regards
holli

**Comment by manup** [comment]
As I understand the lights are mainly controlled via group/broadcasts? Could you please provide a log with APS and INFO enabled over 10-15 minutes where the problem occurs, I'd like to check what is in the APS queue and stalling.

**Comment by stijink** [comment]
Same for me. Massiv problems since a few days. Raspbee 2 on a Raspberry Pi 4, 4 GB. at Software Version 2.19.01. I'm managing around 120 Zigbee devices with that.

**Comment by Tiihokatti** [comment]
Having similar issues on HA deCONZ addon version 12.9.1, hardware is rpi4 + Raspbee II.
Random massive delays while controlling lights. Tried switching from SD-card to SSD, updating Raspbee firmware, turning rpi4 onboard BT/wifi off, removing the last added bulb from network, disabling OTAU, etc.

Logs were showing some kind of delay spam with basic info logging. Activated the proper logging levels now to see what is going on the next time a massive delay hits.
My network is relatively small as I have part of my bulbs connected to 2 Hue bridges (for Ambilight).

**Comment by popy2k14** [comment]
@Smanar thx for the info.

@manup Can you please look at the log above: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6445#issuecomment-1287757829
I had the slow down of my network with ~15%! cpu load instead of 0,5% after addon restart.
There was the following actovated: APS, APS L2 , Error, Error L2, Info, Info L2.

Does deconz running something in an loop which it should'nt?
Any hints about the massive "Skip idle timer callback..." messages?

**Comment by Ltek** [comment]
I dont think this is fixed... I still have large delays with any device command from any app (Phoscon, Homeseer, Hue Essentials) 
 using Conbee v1. When I control the lights individually the response is near instant. using via groups takes 20-30 sec. I use a Windows PC so does not seem hardware specific

**Comment by manup** [comment]
Hi, small update on the problem. There are multiple places in the code base under investigation to track and and fix the filling up of command queue. I'm using my test network with 140 lights and modified DDF files to provoke extensive polling and CPU usage.

The above mentioned ZGP related issue https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6482 is now confirmed to be working. However I've found more similar problems related to schedule commands too rapidly, which fills the outgoing command queue and causes delays, this will be fixed for the next release.

Overall target is that group casts shouldn't suffer noticeable delays because contrary to unicast commands they can just be blasted out and don't have to wait for any acknowledgements from devices. There still needs to be a small artificial delay between group-casts as some devices (~100 milliseconds) don't support receiving too many broadcasts in a short time well.

**Comment by popy2k14** [comment]
Thanks for the update.
Will try the update and give feedback from my rather big network, when it's available.

**Comment by holli73** [comment]
@manup i'm on 2.19.01 now again - but i run with the latest commit - since one day - all 3 env. (x64 (conbee) + pi4 (conbee) + pi3(raspbee)) - and so far it looks good - no delays or missed calls - did occur that my wife was complaining about **gg**

i only use the following 2 call types:
`
urlg='http://192.168.249.1:8080/api/MyIHouseApi/groups/6/action'
urls='http://192.168.249.1:8080/api/MyIHouseApi/groups/6/scenes'
### TURN OFF
curl --tcp-nodelay --max-time 5 -H 'Content-Type: application/json' -X PUT -d '{ "on" : false }' $urlg
### TURN ON (scenes 1-4 are available for all groups (digitalstrom available light switch clicks...))
curl --tcp-nodelay --max-time 5 -H 'Content-Type: application/json' -X PUT $urls/1/recall
`
thanks
holli

**Comment by Tiihokatti** [comment]
Finally managed to salvage my HA backup for Deconz addon (the addons are a docker implementation) from the wreckage of my old main PC which had all the backups stored inside it. It had broken down just when the issue started showing up.

Time to see if this rollback to an older version (2.18.2) will fix this horrible delay bug.

**Comment by Ltek** [comment]
@manup this is not fixed, not even close. I installed 19.2 over 18.2 (which has INSTANT response from all devices)... and 19.2 takes AT LEAST 30 seconds for any devices to get the command.

the only version that is usable is 18.2

I run a Win10 very fast PC with Conbee 1. I've never had delays at all until 19.x

**Comment by Smanar** [comment]
I had this issue too on conbee 1, I have updated the deconz version (like you) and have updated the firmware too.

**Comment by Mimiix** [comment]
@holli73 is this issue fixed for you?

**Comment by holli73** [comment]
@Mimiix - yes/no - i'm still using 2.19.2 but i must restart deconz every 3-4 days as delays occur once restarted the delay is gone - i have automated this restart...

**Comment by popy2k14** [comment]
Running 2.19.1 with official HA addon and today, after ~11 days runtime, the cpu usage of the addon is ~15% instead of 0,2% and my network is slow and unrespnsive again. A simple restart of the deconz addon keeps things back to normal.
I know that upcomming release has optimized a few things but as @holli73 stated, it's not stable.

Here is a pastebin log with INFO, ERROR & APS activated: https://pastebin.com/7Ft21sgs
But as before, nothing interesting inside :-(

How can we help to further debug this long going issue?

@holli73: Does restarting deconz every few days doesn't kick out some devices (like aqara's, xiaomi PIR's)?

@manup and devs: does neither of you have such an issue?

@manup any news on this issue?

**Comment by Mimiix** [comment]
> Running 2.19.1 with official HA addon and today, after ~11 days runtime, the cpu usage of the addon is ~15% instead of 0,2% and my network is slow and unrespnsive again. A simple restart of the deconz addon keeps things back to normal. I know that upcomming release has optimized a few things but as @holli73 stated, it's not stable.
> 
> Here is a pastebin log with INFO, ERROR & APS activated: https://pastebin.com/7Ft21sgs But as before, nothing interesting inside :-(
> 
> How can we help to further debug this long going issue?
> 
> @holli73: Does restarting deconz every few days doesn't kick out some devices (like aqara's, xiaomi PIR's)?
> 
> @manup and devs: does neither of you have such an issue?
> 
> @manup any news on this issue?

Not a dev , but i do see the same. However it doesn't make the network slower but that probably is because deconz has its own Rpi 3b. So yes, i am seeing the same.

**Comment by popy2k14** [comment]
thx for confirming!
I dont know much about the archtiecture of deconz+conbee/raspbee, but i also develop firmware/software on different cpus (Microchip, ST, Atmel, RPI, x86, ...) which talks to each other over different interfaces (USB, serial, SPI, I2C, ...).

In such cases of instabillity of an process, it's hard to find why it takes too much cpu cycles for the main loop or it's threads.
What i can recommend, is to meassure the time of the function calls which get's call from the main loop or other threads.
Print this info to the log, ex.: just when ERROR is activated. this can be done once every 5 seconds to not spam and previously do some math arround each sample for each function (max, min, avg & 99%).

With this method you can easily find the function which goes atomic, when the issue occurs.
Sure, you have to repeat the process, when you found an function, which takes to much time.
Because you have to put the same measurement, into this function again on sub functions.

If the issue is in conbee/raspbee firmware (ex.: is sending to much data to deconz, causing high cpu load).
The same game as described above can be done in the firmware and reporting it to deconz.
For this, the communication between the firmware and daconz must be up running, when the issue occcurs.

It's time consuming, but maybe leads to the right direction.
But well implemented in an debug build with debug defines does'nt hurt release builds and can be used again on performance issues.

@manup any hint's what can cause the excessive cpu load and what's your plan to find it?
Me and others struggling with this since a few months now.

PS.: if there is something we can do to help find this issue, just let us know.

**Comment by manup** [comment]
The bigger issues with high CPU load and memory usage are addressed in v2.19.2-beta, here mainly Qt Javascript and too frequent UI updates and database writes burnt CPU cycles. There is still much to do to get everything in order and replace our legacy parts with proper scheduled ones. In terms of CPU usage we still have heaps of crazy legacy code which needlessly loop over data and hundreds of string comparisons being done on each received command, accumulated over the years before DDF. The goal here is to clean this up over time and reduce complexity to a smaller very robust core around DDF. 

The delays which can be seen in some setups should hopefully be fixed soon.

One step to get rid of group delays is to partition the outgoing command queue so that commands which don't need any ACKs or routing, like group casts, are guaranteed to have a free slot in a given time frame. Also control commands like toggling a light need to get a proper priority over idle tasks which may block the queue until a request is done. A request may take 30 seconds or even more if the node isn't reachable, sleeping or routing needs to be figured out.

**Comment by holli73** [comment]
@popy2k14 - i started years ago and decided only to use 3 kind of light types all are osram lightify (Surface tuneable white/e27 rgbw/gu10 spots tuneable white) - so i only have this types of lights - but this is not completely true any more - as osram is not producing this light devices anymore - i had to replace some broken with ledvance gu spots - but i could not find a good replacement yet for my surface devices - one got replaced with a hue aurelle panel but 95% of my apx 200 lights are still osram.

**Comment by popy2k14** [comment]
@manup Thanks for the detailed answer. The move to DDF is an very nice one! This way devices can easily added without impacting other parts of the core. And if the core is stable it lowers the work needed to find bugs.

Regarding the delays:
I am experiencing those just when my cpu load of the addon is high. So maybe some of the issues are already solved.
Hope you can find the queuing issues and fix them.
If there is anything we can do, just let us know (help debugging on our systems...).
I know what it means if your customers has other "networks" than yours and you try to reproduce an issue and sadly sometimes can't.

Is it possible to add some queuing logging, which can be enabled in the debug view on issues and reports some stats (like described above)?

@holli73
Wow, this is a huge network!
Ok, do you have sensors (PIR, Door/windows, ...)´?
In my case, sometimes after deconz restart they got lost, not often, but it happens 2-3 times a year (depending on how often i update/restart deconz). So automated restart in option for me.
From a developer perspective (ans also user) it's not good when you have to go this brute force way to keep something stable :-) But yes, a workaround, this works for some networks/use-cases.

**Comment by francescopeloi** [comment]
Hi,

I am suffering the same problem and have reported it in the deconz forum: https://forum.phoscon.de/t/communication-lag-raspbee-ii/2975/6

Problem is fixed if I roll back to 2.18.02.

**Comment by rgerbranda** [comment]
I moved all my groups to [Home Assistant](https://www.home-assistant.io/integrations/group/). I still have a delay sometimes, but it is much better.

**Comment by francescopeloi** [comment]
IIRC I read that this is not a great solution as it can flood the network if you have many devices

**Comment by popy2k14** [comment]
@rgerbranda don't do that!
This generates much more traffic than group casts over deconz itself!
The recommended way is to setup groups in deconz and use them in HA.

**Comment by francescopeloi** [comment]
hi @manup ,

is this being fix as part of [v2.20.0-beta](https://github.com/dresden-elektronik/deconz-rest-plugin/tree/v2.20.0-beta)?


In the [bug fixes section of the release notes](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.20.0-beta) it says
> Fix firmware connectivity problems and reduce delays when sending commands.

but it's unclear if it's about this specific issue, as there's no reference to a PR like all the other bug fixes.

Note that many users are stuck with 2.18.x because of this issue.

Thank you for your help.

**Comment by manup** [comment]
Hi @francescopeloi yes the mentioned fix is also to address this issue. But needs more verification to be sure.

v2.20.0-beta should work better, note there are still some places which may cause delays like database writes which depending on the setup may delay for a second on a Raspberry Pi SD-card (this will be addressed in a future release).

**Comment by francescopeloi** [comment]
thank you @manup , I am going to install the beta today and will let you know if it improves the situation with my setup

**Comment by francescopeloi** [comment]
hey @manup , so far it looks promising, after more than 24 hours I haven't encountered the bug/any delay yet with 2.20.0-beta. Usually it was happening quite often with my setup. I am going to monitor it a few more days just to be sure, will report back.

Quick side notes:

- https://phoscon.de/en/changelog/ seems not updated, maybe better to just link out to [github releases](https://github.com/dresden-elektronik/deconz-rest-plugin/releases) from there?
- on deconz web UI, if I click on left hamburger menu icon -> gateway, next to "version" I see the wrong date, it says: Version 2.20.00 / 19/09/2022

**Comment by manup** [comment]
Hi, thanks for reporting back. Sounds good so far, hope it resolves various similar issues which were reported.

>Quick side notes:
>    https://phoscon.de/en/changelog/ seems not updated, maybe better to just link out to [github releases](https://github.com/dresden-elektronik/deconz-rest-plugin/releases) from there?
>    on deconz web UI, if I click on left hamburger menu icon -> gateway, next to "version" I see the wrong date, it says: Version 2.20.00 / 19/09/2022

Indeed these lack behind currently, will be fixed soon.

**Comment by popy2k14** [comment]
@manup Running latest stable v2.19.3 and the slow downs are way better than before. But sometimes it happens. Not as frequently as in the previous v2.19.x but it happens.

Can you please release the latest v2.20.0 as soon as possible to the stable channel?
So also HA users, which are forced to use the stable, can profit from the latest commits regarding the slowdown issue.

**Comment by Mimiix** [comment]
> @manup Running latest stable v2.19.3 and the slow downs are way better than before. But sometimes it happens. Not as frequently as in the previous v2.19.x but it happens.
> 
> Can you please release the latest v2.20.0 as soon as possible to the stable channel? So also HA users, which are forced to use the stable, can profit from the latest commits regarding the slowdown issue.

I think he plans to do so in a few days.

HA using only stable (and no option to manually pick any other version) is the reason why i moved away from the Addon and started using deCONZ on a seperate VM.

**Comment by Krocko** [comment]
@Mimiix can you please explain this?
> started using deCONZ on a seperate VM

**Comment by Mimiix** [comment]
> @Mimiix can you please explain this?
> 
> > started using deCONZ on a seperate VM

I have a Synology Nas (DS218+) running 2 VM's : 1 with Home ASsistant OS, running HA. The other with Raspbian and installing deCONZ on there.  Currently, as my nas had issues with performance on my NAS and watching videos, i moved deCONZ to a RPI. but it all worked fine. 

The Home Assistant Integration takes care of the connection between HA and deCONZ. You don't need the Addon at all.

**Comment by manup** [comment]
Hi, stable [v2.20.1](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.20.1) is now released. Should be up in the add-on soon.

**Comment by popy2k14** [comment]
> > @manup Running latest stable v2.19.3 and the slow downs are way better than before. But sometimes it happens. Not as frequently as in the previous v2.19.x but it happens.
> > Can you please release the latest v2.20.0 as soon as possible to the stable channel? So also HA users, which are forced to use the stable, can profit from the latest commits regarding the slowdown issue.
> 
> I think he plans to do so in a few days.
> 
> HA using only stable (and no option to manually pick any other version) is the reason why i moved away from the Addon and started using deCONZ on a seperate VM.

Yeah, sadly there is no beta/version option in the addon.
But i dont want to miss the supervised docker addons.
They are neat, easy to backup and restore.
I have gone the other way, just because to lower the admin work. Ditched my PI with deconz and moved into tzhe addon on my odroid N2+.

> Hi, stable [v2.20.1](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.20.1) is now released. Should be up in the add-on soon.

Thx a lot!

**Comment by francescopeloi** [comment]
hi @manup , unfortunately I saw the problem happening after a few days. I had a deconz restart cronned every morning, which I removed. This might have helped the days before I guess. So I can confirm that the problem is still happening with 2.0.0-beta with my setup.

**Comment by Mimiix** [comment]
> hi @manup , unfortunately I saw the problem happening after a few days. I had a deconz restart cronned every morning, which I removed. This might have helped the days before I guess. So I can confirm that the problem is still happening with 2.0.0-beta with my setup. So far I might say that they are not as frequent as before, but it's a bit of a guess.

What are you seeing? 


I have 2.20 and my delays after a few days are gone.

Did you rule out any power off devices , or devices with bad lqi?

**Comment by vbaros** [comment]
@francescopeloi what is your hardware and software setup? Also which exactly power supply are you using on the machine Conbee is connected to?

**Comment by francescopeloi** [comment]
I wrote an extended description here: https://forum.phoscon.de/t/communication-lag-raspbee-ii/2975

**Comment by vbaros** [comment]
Interestingly enough I had exactly the same issue as you. Sudden lag if about 30 to about 69 seconds. Then suddenly the commands would get replayed, but sometimes even not.

 Missing fr your configuration only the power supply. I did not see it in your description.

At the end I moved everything to the Intel Nuc. It is not even the most powerful one. Pentium with 4 cores. I've installed Proxmox and set up HA in the virtual machine and installed Deconz docker container inside a separate Linux container. Since then literally 0 problems. It works amazingly.

**Comment by francescopeloi** [comment]
I need to apologies, the problem with 2.20 was caused by a mis-behaving motion sensors. All seems to be fine with 2.20.0 now.

**Comment by manup** [comment]
Closing this for now as the delays have been addressed in previous issues.
