### ISSUE TITLE
Since versions v2.19.0-beta and v2.19.1, several devices do no longer work properly

### ISSUE THREAD

**Issue by Rolf56** [dresden-elektronik/deconz-rest-plugin#6461]
## Describe the bug
Since versions v2.19.0-beta and v2.19.1, the following devices do no longer work properly:

- Hersteller: Philips, Produkt: Dimmschalter, Version: 6.1.1.28573
- Hersteller: Philips, Produkt: Dimmschalter, Version: 5.45.1.17846
- Hersteller: LUMI, Produkt: lumi.switch.n2aeu1, Version 0.0.0_0022

These are recognized by the system, but can no longer be switched locally.
The relay in the Lumi switch clicks and the blue lamp comes on, but the light command is not executed.
The LED on the Dimmschalter lights up red.

## Steps to reproduce the behavior
it works with version v2.18.2. After the installation of one of the newer version it doesn't work anymore.
Deconz is conected to FHEM and controld by it.

## Environment
 - Host system: PC
 - Running method:  Windows
 - Firmware version: 26400500
 - deCONZ version: 2.19.01
 - Device: ConBee I
 - Do you use an USB extension cable:  no
 - Is there any other USB or serial devices connected to the host system? no

**Comment by SVH-Powel** [comment]
I have a lot of these dimmers and I stay with version 2.18.2 for the moment. Better safe than sorry....

Can anyone confirm what @Rolf56 reports? Is this an issue with 2.19? (or conbee I or perhaps Rolf56 system only)

**Comment by AndreHamburger** [comment]
Confirmed. After updating to 2.19 HUE Button still appears as a device / switch, but without function. Button is blinking  2 times green, but no assigned actions will be performed. Deleting the Button is also not working properly. Seems cache is beating and device is back visible as a switch, after deleting it and rebooting the Rasperry PI. Homebridge is sometimes providing websocket errors. I my perception is, the Raspberry slows down and CPU usage increased, once several button clicks has been made. Other switches (Opodo) working properly and lights and scenes are fine too

**Comment by le-clu** [comment]
Same issue. NONE of my devices seem to work.

Using RaspBee with Home Assistant.

Is there any known and good way to downgrade?

**Comment by Mincka** [comment]
> Is there any known and good way to downgrade?

Restore a backup. If don't use the Google Backup Add-on, don't uncheck the backup option when you update an add-on. Good luck.

**Comment by therealhalifax** [comment]
Same for me with the HUE SMART BUTTON. Also pairing dosnt work. Downgrade helped.

**Comment by ebaauw** [comment]
My Hue smart button works without any issue in v2.19.1.

For the Hue smart button, please:
- Please double-check in the GUI that deCONZ receives button action notifications on the 0xFC01 cluster.  If not, double-check that the 0x0031 _Configuration_ attribute in the _Basic_ cluster is 0x000b;
![Untitled](https://user-images.githubusercontent.com/22179355/199556962-1fd219eb-9d67-4d23-9240-34be2c2d831a.jpg)

- Double-check that it reports `manufacturername` of "Signify Netherlands B.V." (not: "Philips").  If not, read the _Basic_ cluster attributes, while pressing the button, ensuring that it's awake;
![Untitled1](https://user-images.githubusercontent.com/22179355/199556994-c7fec3d3-1dfe-44b6-8232-aaec5cb5c1d2.jpg)

- Double-check that it uses the correct DDF, `philips_rom001_smart_button.json`.  The DDF should define four bindings.

If all these check out, and the API still doens't emit buttonevent notifications, please:
- List the API ZHASwitch `sensors` resource for the button;
```
{
  "config": {
    "battery": 100,
    "group": "10",
    "on": true,
    "reachable": true
  },
  "etag": "99282fc5781bd2fb7fc2812f30b69bc7",
  "lastannounced": "2022-11-02T17:02:23Z",
  "lastseen": "2022-11-02T17:15Z",
  "manufacturername": "Signify Netherlands B.V.",
  "mode": 1,
  "modelid": "ROM001",
  "name": "Living Room Button",
  "state": {
    "buttonevent": 1002,
    "eventduration": 1,
    "lastupdated": "2022-11-02T17:07:10.297"
  },
  "swversion": "2.47.8_h2F968624",
  "type": "ZHASwitch",
  "uniqueid": "00:17:88:01:06:07:b6:c4-01-fc00"
}
```
- Capture the APS and APS_L2 log in deCONZ, while pressing the button:
```
Nov 02 18:07:10 pi2 deCONZ[25970]: 18:07:10:111 APS-DATA.indication srcAddr: 0xb302, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 255, rssi: -58
Nov 02 18:07:10 pi2 deCONZ[25970]: 18:07:10:112 	asdu: 1d0b104a000100003000210000
Nov 02 18:07:10 pi2 deCONZ[25970]: 18:07:10:143 [INFO] - No button map for: ROM001, unicast to: 0x0000, endpoint: 0x01, cluster: 0xFC00, command: 0x00, payload: 0100003000210000, zclSeq: 74
Nov 02 18:07:10 pi2 deCONZ[25970]: 18:07:10:144 Websocket 127.0.0.1:47430 send message: {"attr":{"lastseen":"2022-11-02T17:07Z"},"e":"changed","id":"229","r":"sensors","t":"event","uniqueid":"00:17:88:01:06:07:b6:c4-01-fc00"} (ret = 2044751104)
Nov 02 18:07:10 pi2 deCONZ[25970]: 18:07:10:150 Websocket 127.0.0.1:47430 send message: {"e":"changed","id":"229","r":"sensors","state":{"buttonevent":1000,"eventduration":0,"lastupdated":"2022-11-02T17:07:10.126"},"t":"event","uniqueid":"00:17:88:01:06:07:b6:c4-01-fc00"} (ret = 2044751104)
```

**Comment by Pirol62** [comment]
Hi, I'm using these switches in Home Assistant.
Opening the DDF in deConz providing these Info:
![image](https://user-images.githubusercontent.com/48820003/199666520-685a35f8-ff4e-4898-9ea0-a5ae2ead43a5.png)
IT's definately another json
That's the preview:
![image](https://user-images.githubusercontent.com/48820003/199667147-d94410fe-be25-4e87-aa43-93c6d0ab296f.png)
What shall I do now?

**Comment by ebaauw** [comment]
That’s an old-model Hue dimmer switch, not a Hue smart button.  Afaik there were no changes for this device between 2.18 and 2.19.  I think you might be running into a generic issue, not one related to a particular device.  There are known issues with send queues filling up in 2.19, causing outgoing commands to be dropped by the gateway.  In this case, the ZHASwitch state would be updated alright (and the corresponding web socket notifications would be sent), but any actions by related rules would be lost.

This would affect all switches that behave like sensors, reporting button events to the gateway and requiring some automation (rules) to control lights.  It would not affect switches that behave like controllers, sending commands directly to bound groups or lights, without going through the gateway.

**Comment by Pirol62** [comment]
By the way: I'm working with deConz not ZHA. Maybe that's a difference and the hue dimmer switch doesn't provide events anymore compared to my Aquara Switches, which are working as usual.

**Comment by therealhalifax** [comment]
I have also deconz, not zha and just by the update some devices not working anymore and not pairable anymore. After downgrade it works again. So no change in anything excapt the deconz addon.

**Comment by AndreHamburger** [comment]
Just FYI. I updated just Node.js to the latest version for Rasperry Pi to 18.12.1, as while i updated Deconz to 2.19.1 at the same time Node was updaten to 18.2.0. But no effect for the HUE Button issue. Still not working, same websocket errors occurred in Homebridge

**Comment by IgnacioHR** [comment]
I’ve the same issue with ROM001 (Smart Switch) devices. I documented here
https://forum.phoscon.de/t/hue-smart-switch-rom001-no-longer-work-in-version-2-19-01/2706
but have no solution. I downgraded to previous version

**Comment by AndreHamburger** [comment]
Sorry, being a newbi….can someone mention, how to downgrade to 2.18.2 on Rasperry, to make hue button working again?

**Comment by IgnacioHR** [comment]
@AndreHamburger I downloaded the .deb file and executed apt install ….deb sorry for lack of formatting cause I’m on my mobile phone

**Comment by Friedi1970** [comment]
> @AndreHamburger I downloaded the .deb file and executed apt install ….deb sorry for lack of formatting cause I’m on my mobile phone

Which .deb? Apt install? Could you describe more precise pls.?

**Comment by IgnacioHR** [comment]
@Friedi1970 @AndreHamburger 

Head here:

http://deconz.dresden-elektronik.de/raspbian/beta/

And select the version you want to downgrade to.

Copy that file in the RPI you want to install it and run `sudo apt install ....deb` where ... is the file you just downloaded. The process will ask you if you are sure you want to downgrade.

Note, do it at your own risk! For example, if the new version updates the database schema, the old version might not work.  It is always a good practice to do a backup copy of the `.local/share/dresden-elektronik/deCONZ` directory (I'm not an expert so there might be other directories with important information). In my case, going back from 2.19.1 to 2.17.1 caused no issues.

**Comment by Friedi1970** [comment]
> @Friedi1970 @AndreHamburger
> 
> Head here: ...

Thanks a lot!!!

**Comment by Friedi1970** [comment]
> @Friedi1970 @AndreHamburger
> 
> Head here:
> 
> http://deconz.dresden-elektronik.de/raspbian/beta/
> 
> And select the version you want to downgrade to.
> 
> Copy that file in the RPI you want to install it and run `sudo apt install ....deb` where ... is the file 

When I try to run sudo apt the command apt is unknown ...

**Comment by IgnacioHR** [comment]
just `apt` works for me, try `apt-get` instead

**Comment by MSchmitt67** [comment]
> Sorry, being a newbi….can someone mention, how to downgrade to 2.18.2 on Rasperry, to make hue button working again?

i downgraded to 2.18.02  =

1.
sudo systemctl stop deconz **(Headless version)**, or
sudo systemctl stop deconz-gui **(GUI version)**

2.
wget -O deconz-2.18.02-qt5.deb https://deconz.dresden-elektronik.de/raspbian/stable/deconz-2.18.02-qt5.deb

3.
sudo dpkg -i deconz-2.18.02-qt5.deb

4.
sudo systemctl start deconz

**Comment by Friedi1970** [comment]
I neither have the commands apt nor apt-get nor dpkg :(
I just get: 
sudo: dpkg: command not found

**Comment by MSchmitt67** [comment]
wich system you are on ?

**Comment by Friedi1970** [comment]
> wich system you are on ?

HA OS

**Comment by MSchmitt67** [comment]
Raspberry Pi ?
Conbee 2 ?

**Comment by Friedi1970** [comment]
yep

**Comment by Mimiix** [comment]
Ha os doesn't have this options afaik.

**Comment by Friedi1970** [comment]
> Ha os doesn't have this options afaik.

Unfortunately I guess you're right :-/

**Comment by IgnacioHR** [comment]
I tested version 2.19.2 yesterday but the problem with the HUE Smart Switch ROM001 persist. I updated firmware of the HUE to match the one @ebaauw showed here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6461#issuecomment-1300977974 

I request to reopen this bug

**Comment by IgnacioHR** [comment]
Downgrading to version 2.18.02 does NOT fix the issue. Downgrading to 2.17.01 fixes it

**Comment by Tscherno** [comment]
> I tested version 2.19.2 yesterday but the problem with the HUE Smart Switch ROM001 persist. I updated firmware of the HUE to match the one @ebaauw showed here: [#6461 (comment)](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6461#issuecomment-1300977974)
> 
> I request to reopen this bug

Same for me. All the Buttons stopped working after upgrading to 2.19.2. Reset / Readding not possible. After downgrade to 2.17.01 its working again. Had to reconfigure the actions of all buttons afterwards.

**Comment by Wiggerl26** [comment]
I had exact same problem with my HUE Smart Switch, but it started working again after firmware update to 2.47.8_h2F968624. You can find the firmware here: https://github.com/dresden-elektronik/deconz-ota-plugin#hue-firmware.

**Comment by Tscherno** [comment]
Does that work if they are not connected anymore or not connected at all?!?

**Comment by Wiggerl26** [comment]
Let me be a bit more precise: I downgraded deconz to 2.17 and deleted the smart button in phoscon app. Then I upgraded deconz to 2.19.2 and paired the button again using phoscon app. After that my button started working in openhab again.

**Comment by Sergeus** [comment]
I have also had to downgrade back to 2.17, because all of my Hue Smart Buttons stopped working on 2.19.1. Downgrading has restored their functionality.

I tried the steps mentioned by ebaauw, but several behaviors diverged from those instructions. The Configuration value on the Basic cluster for several of my siwtches is 0x0000. Reading the Basic cluster again did not change this. Rereading the Basic cluster caused the Manufacturer to change to Philips, not Signify. The DDF json for the buttons looks much more like the one posted by Pirol62 (though not exactly the same).
![image](https://user-images.githubusercontent.com/931014/202906027-0e482298-d471-4c56-b330-a7e41cc644d7.png)

Several of my Hue Buttons are on older firmwares (none are on 2.47.8, which is what's listed on that firmware list page - the highest is 2.30, lowest seems to be 2.21), but trying to do any firmware updates via deConz did not work for me. Is there a reliance on a specific firmware version now for some updated information?

At the high level, even if we can fix it (and right now I can't) this seems like a significant breaking change for existing users. Is there anything that future versions can do for some backwards compatibility? Or a migration path to what seems to be a new way for deConz to communicate with these Hue devices?

**Comment by Smanar** [comment]
Your DDf is not used, look at the status "Draft" if you want to use it set it to "Gold", and with the DDF the manufacture name need to be "Philips"

**Comment by ebaauw** [comment]
>  Reading the Basic cluster again did not change this.

Make sure to press the button to wake the device.

> Is there a reliance on a specific firmware version now for some updated information?

I suspect Signify might have changed the _Manufacturer Name_ with the latest firmware version.  I only have one button, which is on the latest firmware, so I cannot verify this myself.

> Is there anything that future versions can do for some backwards compatibility?

Change the DDF to accept both "Signify Netherlands B.V."/"ROM001" and "Philips"/"ROM001" as `manufacturername`/`modelid`:
```
{
    "schema": "devcap1.schema.json",
    "manufacturername": [
        "$MF_SIGNIFY",
        "$MF_PHILIPS"
    ],
    "modelid": [
        "ROM001",
        "ROM001"
    ],
    "product": "Hue smart button",
    "status": "Gold",
    "sleeper": true,
    "subdevices": [
        ...
    ]
}
```

**Comment by IgnacioHR** [comment]
Most of us (users) don’t understand how to modify DDF files. Maybe is a good idea to include an updated one with the next version?

**Comment by ebaauw** [comment]
If someone can confirm that indeed the older firmware versions advertise "Philips" as _Manufacturer Name_.

**Comment by IgnacioHR** [comment]
It is confirmed!

https://forum.phoscon.de/t/hue-smart-switch-rom001-no-longer-work-in-version-2-19-01/2706

**Comment by ebaauw** [comment]
No, it hasn’t. I want to see a GUI screenshot of the _Basic_ cluster.  There’s still some crooked logic in the API plugin that sets manufacturername based on the MAC address prefix, before the _Basic_ cluster has been read.

**Comment by Sergeus** [comment]
Here's confirmation:
![image](https://user-images.githubusercontent.com/931014/203069754-e081474b-bfb6-4ec0-a7fa-e48713020c6e.png)
That button is running 2.25.0_r30044 (according to Phoscon). The above screenshot was taken after pressing "Read" while holding down the button. This also shows that Configuration remains at 0x0000.

Before pressing "Read" most of those values were blank or invalid, like so:
![image](https://user-images.githubusercontent.com/931014/203070447-1be1c947-6eca-4ddc-a934-1c0bb462efcd.png)

**Comment by ebaauw** [comment]
@Sergeus, thanks!

Damn Signify.  It would explain why I originally created the DDF for "Philips" in #6164, before changing it to "Signify Netherlands B.V." in #6347.  I thought I made an error, but apparently the manufacturer name changed between firmware versions.

@Rolf56 Why are you posting screenshots of the original model Hue dimmer switch?

**Comment by ebaauw** [comment]
This PR should math both manufacturer names.  I sure hope we won't see too many other devices with this "feature".

**Comment by Rolf56** [comment]
@ebaauw
because I opend this issue initualy and still got no answer for a solution!

**Comment by ebaauw** [comment]
Damn, indeed.  I fear they hijacked your issue for the Hue smart button.  You're running older firmwares on your Hue dimmer switches, but the old model still advertises as "Philips" with the latest fiirmware, so your issue is unrelated to the issue with the smart button.

Still, the same questions as in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6461#issuecomment-1300977974, except for the _Manufacturer Name_ part.

**Comment by ebaauw** [comment]
It’s not the predating, but the change that bothers me.  The Hue bridge exposes the new `manufacturername` for all Hue devices, but they didn’t change the _Manufacturer Name_ on the firmware of the old devices.  At least not for the old models of the Hue dimmer switch and Hue motion sensor.  And some of the newer devices (like latest Hue Bloom) still use “Philips” with the latest firmware.  It’s a jungle out there…

I wish the DDF would simply match both “Signify Netherlands B.V.” and “Philips” on either value.

**Comment by Rolf56** [comment]
@https://github.com/ebaauw 
I have compared the DDF files of the two versions. There is no difference. I don't think that the problem arises because of the DDF file.
Therefore, something must have been changed in the deConz code that causes this different behavior.
Can you give the issue to SW development to check this?

**Comment by ebaauw** [comment]
There is no difference in handling the Hue dimmer switch between recent versions of deCONZ.  We’re seeing a good deal of issues where deCONZ becomes unresponsive because of queues on the coordinator device filling up, and the API plugin (re-)queuing requests too frequently.  That’s what the PR that closed this issue addresses (in part).

Still we need to assess whether your issue is caused by the communication between the Hue dimmer switch and deCONZ, or between deCONZ and the lights.  Hence my questions above.  Also, do you see any errors in the deCONZ log?

**Comment by Rolf56** [comment]
Here the messages from APS and APS_L2. ERROR and ERROR_L2 are empty

APS
====
16:15:24:274 APS-DATA.indication srcAddr: 0x9e63, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x000C, lqi: 127, rssi: -75
16:15:24:294 APS-DATA.indication srcAddr: 0x9e63, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x000C, lqi: 127, rssi: -75
16:15:24:336 APS-DATA.indication srcAddr: 0x9e63, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x000C, lqi: 199, rssi: -66
16:15:24:416 APS-DATA.confirm id: 7, status: 0x00 SUCCESS
16:15:24:416 APS-DATA.confirm request id: 7 -> confirmed, timeout 625297673
16:15:24:448 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 0, rssi: 98
16:15:24:448 APS-DATA.indication request id: 7 -> finished
16:15:24:448 APS-DATA.request id: 7 erase from queue
16:15:24:448 APS-DATA.request id: 28, addrmode: 0x03, addr: 0x00212effff01ba30, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 5 len: 2 tx.options 0x00
16:15:24:512 APS-DATA.confirm id: 22, status: 0x00 SUCCESS
16:15:24:513 APS-DATA.confirm request id: 22 -> erase from queue
16:15:24:523 APS-DATA.confirm id: 28, status: 0x00 SUCCESS
16:15:24:523 APS-DATA.confirm request id: 28 -> confirmed, timeout 625340459
16:15:24:539 reject aps request to enddevice node queue is full (4)
16:15:24:554 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0000, lqi: 0, rssi: 98
16:15:24:554 APS-DATA.request id: 22 erase from queue
16:15:24:554 APS-DATA.request id: 31, addrmode: 0x02, addr: 0x0000, profile: 0x0104, cluster: 0x0000, ep: 0x01 -> 0x01 queue: 5 len: 18 tx.options 0x00
16:15:24:586 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 0, rssi: 98
16:15:24:586 APS-DATA.indication request id: 28 -> finished
16:15:24:586 APS-DATA.request id: 28 erase from queue
16:15:24:586 APS-DATA.request id: 33, addrmode: 0x03, addr: 0x00212effff01ba30, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 5 len: 2 tx.options 0x00
16:15:24:656 APS-DATA.confirm id: 31, status: 0x00 SUCCESS
16:15:24:656 APS-DATA.confirm request id: 31 -> erase from queue
16:15:24:672 APS-DATA.confirm id: 33, status: 0x00 SUCCESS
16:15:24:672 APS-DATA.confirm request id: 33 -> confirmed, timeout 625340602
16:15:24:695 aps request id: 31 finished, erase from queue
16:15:24:695 APS-DATA.request id: 34, addrmode: 0x02, addr: 0x058f, profile: 0x0000, cluster: 0x0001, ep: 0x00 -> 0x00 queue: 5 len: 5 tx.options 0x00
16:15:24:699 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0000, lqi: 0, rssi: 98
16:15:24:726 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 0, rssi: 98
16:15:24:726 APS-DATA.indication request id: 33 -> finished
16:15:24:726 APS-DATA.request id: 33 erase from queue
16:15:24:726 APS-DATA.request id: 37, addrmode: 0x03, addr: 0x00212effff01ba30, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 5 len: 2 tx.options 0x00
16:15:24:785 APS-DATA.confirm id: 34, status: 0x00 SUCCESS
16:15:24:801 APS-DATA.confirm request id: 34 -> confirmed, timeout 625340705
16:15:24:805 APS-DATA.confirm id: 37, status: 0x00 SUCCESS
16:15:24:805 APS-DATA.confirm request id: 37 -> confirmed, timeout 625340746
16:15:24:836 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 0, rssi: 98
16:15:24:836 APS-DATA.indication request id: 37 -> finished
16:15:24:836 APS-DATA.request id: 37 erase from queue
16:15:24:836 APS-DATA.request id: 39, addrmode: 0x03, addr: 0x00212effff01ba30, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 5 len: 2 tx.options 0x00
16:15:24:867 APS-DATA.indication srcAddr: 0x058f, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8001, lqi: 103, rssi: -78
16:15:24:867 APS-DATA.indication request id: 34 -> finished
16:15:24:867 APS-DATA.request id: 34 erase from queue
16:15:24:913 APS-DATA.confirm id: 39, status: 0x00 SUCCESS
16:15:24:929 APS-DATA.confirm request id: 39 -> confirmed, timeout 625340859
16:15:24:946 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 0, rssi: 98
16:15:24:961 APS-DATA.indication request id: 39 -> finished
16:15:24:961 APS-DATA.request id: 39 erase from queue
16:15:24:961 APS-DATA.request id: 42, addrmode: 0x03, addr: 0x00212effff01ba30, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 4 len: 2 tx.options 0x00
16:15:25:258 APS-DATA.request id: 43, addrmode: 0x03, addr: 0x00158d0003f3e837, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x01 queue: 5 len: 5 tx.options 0x00

16:15:45:039 aps request id: 19 failed, erase from queue
16:16:20:134 APS-DATA.confirm id: 19, status: 0x00 SUCCESS
16:16:20:134 APS-DATA.confirm id: 19, status: 0x00, match: 0
16:16:20:165 APS-DATA.indication srcAddr: 0x9b14, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x0013, lqi: 39, rssi: -86
16:16:20:196 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 108, rssi: 0
16:16:20:196 APS-DATA.indication request id: 42 -> finished? not confirmed
16:16:20:231 APS-DATA.indication srcAddr: 0x9b14, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 39, rssi: -86
16:16:20:258 APS-DATA.indication srcAddr: 0x9b14, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0xFC00, lqi: 7, rssi: -91
16:16:20:273 APS-DATA.request id: 53, addrmode: 0x01, addr: 0x0016, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0xFF queue: 6 len: 3 tx.options 0x00
16:16:20:336 APS-DATA.confirm id: 43, status: 0x00 SUCCESS
16:16:20:339 APS-DATA.confirm request id: 43 -> erase from queue
16:16:20:367 APS-DATA.confirm id: 46, status: 0x00 SUCCESS
16:16:20:367 APS-DATA.confirm request id: 46 -> confirmed, timeout 625356644
16:16:20:383 aps request id: 43 finished, erase from queue
16:16:20:398 APS-DATA.indication srcAddr: 0x058f, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 103, rssi: -78
16:16:20:430 APS-DATA.indication srcAddr: 0xd16f, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8001, lqi: 111, rssi: -77
16:16:20:430 APS-DATA.indication request id: 46 -> finished
16:16:20:430 APS-DATA.request id: 46 erase from queue
16:16:20:570 APS-DATA.request id: 56, addrmode: 0x02, addr: 0x21ba, profile: 0x0000, cluster: 0x0001, ep: 0x00 -> 0x00 queue: 5 len: 5 tx.options 0x00
16:16:20:648 APS-DATA.confirm id: 56, status: 0x00 SUCCESS
16:16:20:648 APS-DATA.confirm request id: 56 -> confirmed, timeout 625396582
16:16:20:711 APS-DATA.indication srcAddr: 0x21ba, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8001, lqi: 159, rssi: -71
16:16:20:711 APS-DATA.indication request id: 56 -> finished
16:16:20:711 APS-DATA.request id: 56 erase from queue
16:16:20:742 APS-DATA.confirm id: 53, status: 0x00 SUCCESS
16:16:20:758 aps request id: 53 finished, erase from queue
16:16:20:773 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x01 dstAddrMode: 1, profile: 0x0104, cluster: 0x0006, lqi: 159, rssi: -71
16:16:21:133 APS-DATA.indication srcAddr: 0x5aea, srcEp: 0x03 dstAddrMode: 2, profile: 0x0104, cluster: 0x0702, lqi: 47, rssi: -85
16:16:21:258 APS-DATA.request id: 60, addrmode: 0x03, addr: 0x00158d0003f3e837, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x02 queue: 4 len: 5 tx.options 0x00
16:16:21:355 APS-DATA.confirm id: 60, status: 0x00 SUCCESS
16:16:21:357 APS-DATA.confirm request id: 60 -> erase from queue
16:16:21:383 APS-DATA.indication srcAddr: 0x058f, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 103, rssi: -78
16:16:21:383 APS-DATA.request id: 60 erase from queue
16:16:21:680 APS-DATA.indication srcAddr: 0x5aea, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0102, lqi: 47, rssi: -85
16:16:22:352 APS-DATA.request id: 63, addrmode: 0x03, addr: 0x0017880103b5dba3, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x0B queue: 4 len: 5 tx.options 0x00
16:16:22:433 APS-DATA.confirm id: 63, status: 0x00 SUCCESS
16:16:22:435 APS-DATA.confirm request id: 63 -> erase from queue
16:16:22:455 aps request id: 63 finished, erase from queue
16:16:22:461 APS-DATA.indication srcAddr: 0x0c94, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 159, rssi: -71
16:16:22:570 APS-DATA.request id: 65, addrmode: 0x03, addr: 0x0017880103b5dba3, profile: 0x0104, cluster: 0x0000, ep: 0x01 -> 0x0B queue: 4 len: 5 tx.options 0x00
16:16:25:362 aps request id: 42 prf: 0x0000 cl: 0x0031 timeout (confirmed: 0) to 0x00212EFFFF01BA30 (0x0000)
16:16:25:446 aps request id: 42 failed, erase from queue
16:16:25:446 emit artificial APSDE-DATA.confirm id: 42
16:16:25:539 aps request id: 42 failed, erase from queue
16:16:25:633 APS-DATA.request id: 66, addrmode: 0x03, addr: 0x00212effff01ba30, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 4 len: 2 tx.options 0x00

APS-L2
======
16:17:29:289 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2
16:17:29:320 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2
16:17:29:383 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2
16:17:29:445 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2
16:17:29:508 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2
16:17:29:570 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2
16:17:29:637 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2
16:17:29:695 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2
16:17:29:758 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2
16:17:29:820 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2
16:17:29:883 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2
16:17:29:945 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2
16:17:30:008 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2

**Comment by Mimiix** [comment]
Re-opened as it seems to still affect users.

**Comment by DoCheckor** [comment]
Hi guys! Updated HomeAssistant and the Phoscon firmware for my Conbee2 yesterday and now my Philips Dimmer Switches don't work anymore like they did for months. Better said, only the last one I rebind happens to work

**Comment by Brian-lub** [comment]
i have lost the connection to all mine and i can't get them to reconnect, i have updated downgraded updated, and i have tried everything know. 
running HA with DeConz
Version 2.19.01 / 19.9.2022
Firmware 26720700

**Comment by ebaauw** [comment]
> 16:17:29:289 Delay APS request id: 134 to 0x21BA, profile: 0x0000 cluster: 0x0021 node already has busy 2

That looks suspiciously like queus on the coordinator device filling up, due to issues in v2.19.0 to v2.19.2.  Hopefully, this won’t happen anymore in v2.19.3.

To clear the queus, you need to reset the coordinator device.  Easiest way to do this is to power cycle it.  For the ConBee: stop deCONZ, remove the stick, wait 5s, re-insert it, start deCONZ.  For the RaspBee: shutdown the Pi, remove the power adapter plug from the Pi, wait 5s, re-insert it and wait for the Pi to boot.

**Comment by undulattice** [comment]
Just updated to 2.19.3.
Philips Hue Smart Button still isn't found. :-(

**Comment by ebaauw** [comment]
That’s to be expected; PR hasn’t been merged.

**Comment by tkintscher** [comment]
I have a similar issue, but not quite... for me the difference between working and non-working Hue dimmer switches is the firmware version.

Running deCONZ v2.19.3-beta.
I have three "old" Philips dimmer switches here (RWL021). All of them show the Manufacturer Name as "Philips".

- one has SW Build ID 5.45.1.16265
  - button presses show up on the 0xFC00 cluster in deCONZ
  - button presses show up on the WebSocket
  - rules are executed
  - all good :)

- two have SW Build ID 5.45.1.17846
  - the button presses are registered on the 0xFC00 cluster in deCONZ
  - button presses do *not* show up on the WebSocket
  - rules are *not* executed
  - they used to work before, now they don't ...

I don't understand why the firmware build on the switch would make this kind of difference, though.

**Comment by Pirol62** [comment]
I already updated the conbee firmware to 26780700 but without effect.
Hue dimmer switches cannot be paired and the existing, already paired one, doesn't work with the origin switch modes

**Comment by Pirol62** [comment]
Ok, I already updated deconz addon in HA to 2.19.3 and my Hue Dimmer Switch could be reconnected and works as usual.
So I deleted and reconnected the second Dimmer Switch and everything worked again as well.
For me, this part of the issue is solved.

**Comment by ge8020** [comment]
Smart Button still not functional here with HA and deconz addon 6.17.1 (deconz 2.19.3). When i delete it and pair it new on 2.19.3 it ist recognized as a philips dimmer switch instead of smart button by phoscon. But there are still no events triggered in Home assistant...

**Comment by Friedi1970** [comment]
> Smart Button still not functional here with HA and deconz addon 6.17.1 (deconz 2.19.3). 

Same here. I wonder whether this will solved this year ...

**Comment by pfrenssen** [comment]
The fix for this has been included in the latest stable release v2.20.1 which came out yesterday.
