### ISSUE TITLE
_TZ3000_pfc7i3kt - Behaves like all the switches are grouped

### ISSUE THREAD

**Issue by sciorty** [dresden-elektronik/deconz-rest-plugin#6886]
## Describe the bug
The device has been correctly paired but when i turn on/off **any** of the switches (from deCONZ or HA GUI) all the remaining 2 turn on/off as well. This does not occours when i manually press the physical switches, in that case they correctly behave as individual switches.

## Steps to reproduce the behavior
Just toggle any of the switches from deCONZ or HA GUI

## Expected behavior
Switches should be toggled individually

## Screenshots

![image](https://user-images.githubusercontent.com/6460914/231754483-9f552181-8d5e-4f7a-a47c-f1caf9af9320.png)

## Environment

 - Host system: Raspberry
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26610700
 - deCONZ version: 2.21.02
 - Device: RaspBee II
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs
No logs changes when toggling the lights

## Additional context

![image](https://user-images.githubusercontent.com/6460914/231754155-b21fb711-a6bf-4d7b-8f47-b887373f24ee.png)

![image](https://user-images.githubusercontent.com/6460914/231754075-7a76ac61-7afb-4ffb-9e30-e522f3558764.png)

**Comment by sciorty** [comment]
Sorry 

> Hi,
> 
> Thanks for the report!
> 
> This is not a bug, this is a device not implemented yet. See : #6886
> 
> I have re-opened the above :)

I0m sorry, which issue did you reopen? You referenced this same issue :)

**Comment by sciorty** [comment]
@Mimiix ?

**Comment by Mimiix** [comment]
Huh?!

I check this morning.

**Comment by Mimiix** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6682 was the one i reopened.

Looks like it was also fixed in last beta ;)

**Comment by sciorty** [comment]
Thanbks for the update. I still have the problem though, i'll ask on https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6682
